"""
criar_popup_modelo_via.py — Cria popups/popup_modelo_via.py
Execute com: python criar_popup_modelo_via.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    COR_FUNDO, COR_PAINEL, COR_CARD,\n",
    "    AMARELO, BRANCO, CINZA_CLARO, CINZA_MEDIO,\n",
    "    AZUL_MEDIO, CINZA_ESCURO,\n",
    "    COR_TEXTO, COR_TEXTO_SEC,\n",
    "    FONTE_SUB, FONTE_PEQ,\n",
    "    MODELOS_VIA,\n",
    ")\n",
    "\n",
    "\n",
    "class PopupModeloVia(tk.Toplevel):\n",
    "    def __init__(self, parent):\n",
    "        super().__init__(parent)\n",
    "        self.title('Modelo de via')\n",
    "        self.configure(bg=COR_FUNDO)\n",
    "        self.resizable(False, False)\n",
    "        self.grab_set()\n",
    "        self.resultado = None\n",
    "        w, h = 460, 200\n",
    "        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()\n",
    "        self.geometry(f'{w}x{h}+{(sw-w)//2}+{(sh-h)//2}')\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x')\n",
    "        corpo = tk.Frame(self, bg=COR_FUNDO)\n",
    "        corpo.pack(fill='both', expand=True, padx=28, pady=20)\n",
    "        tk.Label(corpo, text='Como deseja iniciar o croqui?',\n",
    "                 font=FONTE_SUB, bg=COR_FUNDO, fg=COR_TEXTO).pack(pady=(0,16))\n",
    "        btns = tk.Frame(corpo, bg=COR_FUNDO)\n",
    "        btns.pack()\n",
    "        self._btn(btns, 'Usar modelo de via',\n",
    "                  'Escolha um template pronto\\nde cruzamento ou rua',\n",
    "                  AZUL_MEDIO, self._usar_modelo).pack(side='left', padx=10)\n",
    "        self._btn(btns, 'Desenhar do zero',\n",
    "                  'Canvas vazio, voce desenha\\ntudo manualmente',\n",
    "                  CINZA_ESCURO, self._do_zero).pack(side='left', padx=10)\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x', side='bottom')\n",
    "\n",
    "    def _btn(self, parent, titulo, desc, cor, cmd):\n",
    "        f = tk.Frame(parent, bg=cor, cursor='hand2')\n",
    "        tk.Frame(f, bg=AMARELO, height=3).pack(fill='x')\n",
    "        tk.Label(f, text=titulo, font=('Segoe UI',10,'bold'),\n",
    "                 bg=cor, fg=BRANCO).pack(padx=16, pady=(10,2))\n",
    "        tk.Label(f, text=desc, font=FONTE_PEQ, bg=cor, fg=CINZA_CLARO,\n",
    "                 justify='center').pack(padx=16, pady=(0,12))\n",
    "        for w in [f]+list(f.winfo_children()):\n",
    "            w.bind('<Button-1>', lambda e,c=cmd: c())\n",
    "        return f\n",
    "\n",
    "    def _usar_modelo(self):\n",
    "        self.withdraw()\n",
    "        grid = GridModelos(self.winfo_toplevel())\n",
    "        self.winfo_toplevel().wait_window(grid)\n",
    "        self.resultado = grid.resultado\n",
    "        self.destroy()\n",
    "\n",
    "    def _do_zero(self):\n",
    "        self.resultado = {'icone': 'branco'}\n",
    "        self.destroy()\n",
    "\n",
    "\n",
    "class GridModelos(tk.Toplevel):\n",
    "    def __init__(self, parent):\n",
    "        super().__init__(parent)\n",
    "        self.title('Escolha o modelo de via')\n",
    "        self.configure(bg=COR_FUNDO)\n",
    "        self.resizable(False, False)\n",
    "        self.grab_set()\n",
    "        self.resultado = None\n",
    "        w, h = 680, 560\n",
    "        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()\n",
    "        self.geometry(f'{w}x{h}+{(sw-w)//2}+{(sh-h)//2}')\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x')\n",
    "        cab = tk.Frame(self, bg=COR_PAINEL)\n",
    "        cab.pack(fill='x')\n",
    "        tk.Label(cab, text='Modelos de via', font=FONTE_SUB,\n",
    "                 bg=COR_PAINEL, fg=COR_TEXTO).pack(side='left', padx=16, pady=10)\n",
    "        tk.Label(cab, text='Clique no modelo para iniciar',\n",
    "                 font=FONTE_PEQ, bg=COR_PAINEL, fg=COR_TEXTO_SEC).pack(side='right', padx=16)\n",
    "        gf = tk.Frame(self, bg=COR_FUNDO)\n",
    "        gf.pack(fill='both', expand=True, padx=14, pady=14)\n",
    "        for idx, m in enumerate(MODELOS_VIA):\n",
    "            self._card(gf, m, idx//3, idx%3)\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x', side='bottom')\n",
    "\n",
    "    def _card(self, parent, modelo, row, col):\n",
    "        card = tk.Frame(parent, bg=COR_CARD, cursor='hand2', width=190, height=140)\n",
    "        card.grid(row=row, column=col, padx=6, pady=6, sticky='nsew')\n",
    "        card.grid_propagate(False)\n",
    "        parent.grid_rowconfigure(row, weight=1)\n",
    "        parent.grid_columnconfigure(col, weight=1)\n",
    "        prev = tk.Canvas(card, width=140, height=80, bg='#0D1830', highlightthickness=0)\n",
    "        prev.pack(pady=(10,4))\n",
    "        self._preview(prev, modelo['icone'])\n",
    "        tk.Label(card, text=modelo['nome'], font=('Segoe UI',9,'bold'),\n",
    "                 bg=COR_CARD, fg=COR_TEXTO).pack()\n",
    "        def sel(m=modelo):\n",
    "            self.resultado = m\n",
    "            self.destroy()\n",
    "        card.bind('<Button-1>', lambda e: sel())\n",
    "        prev.bind('<Button-1>', lambda e: sel())\n",
    "        for w in card.winfo_children():\n",
    "            w.bind('<Button-1>', lambda e, m=modelo: self._sel(m))\n",
    "        card.bind('<Enter>', lambda e, f=card: f.config(bg='#2A3060'))\n",
    "        card.bind('<Leave>', lambda e, f=card: f.config(bg=COR_CARD))\n",
    "\n",
    "    def _sel(self, m):\n",
    "        self.resultado = m\n",
    "        self.destroy()\n",
    "\n",
    "    def _preview(self, c, icone):\n",
    "        W, H = 140, 80\n",
    "        cx, cy = W//2, H//2\n",
    "        via = 18\n",
    "        def asf(x1,y1,x2,y2): c.create_rectangle(x1,y1,x2,y2,fill='#606060',outline='')\n",
    "        def cal(x1,y1,x2,y2): c.create_rectangle(x1,y1,x2,y2,fill='#909090',outline='')\n",
    "        def fh(y):\n",
    "            for x in range(0,W,14): c.create_line(x,y,x+8,y,fill=AMARELO,width=1)\n",
    "        def fv(x):\n",
    "            for y in range(0,H,10): c.create_line(x,y,x,y+6,fill=AMARELO,width=1)\n",
    "        if icone=='cruzamento_mais':\n",
    "            cal(0,0,cx-via,cy-via); cal(cx+via,0,W,cy-via)\n",
    "            cal(0,cy+via,cx-via,H); cal(cx+via,cy+via,W,H)\n",
    "            asf(0,cy-via,W,cy+via); asf(cx-via,0,cx+via,H)\n",
    "            fh(cy); fv(cx)\n",
    "        elif icone=='cruzamento_t':\n",
    "            cal(0,0,cx-via,cy-via); cal(cx+via,0,W,cy-via); cal(0,cy+via,W,H)\n",
    "            asf(0,cy-via,W,cy+via); asf(cx-via,0,cx+via,cy+via)\n",
    "            fh(cy); fv(cx)\n",
    "        elif icone=='rua_reta':\n",
    "            cal(0,0,W,cy-via); cal(0,cy+via,W,H)\n",
    "            asf(0,cy-via,W,cy+via); fh(cy)\n",
    "        elif icone=='avenida':\n",
    "            cant=6\n",
    "            cal(0,0,W,cy-via-cant); cal(0,cy+via+cant,W,H)\n",
    "            asf(0,cy-via-cant,W,cy-cant); asf(0,cy+cant,W,cy+via+cant)\n",
    "            c.create_rectangle(0,cy-cant,W,cy+cant,fill='#2A6A2A',outline='')\n",
    "            fh(cy-via//2-cant); fh(cy+via//2+cant)\n",
    "        elif icone=='rotatoria':\n",
    "            cal(0,0,W,H)\n",
    "            r_e=min(cx,cy)-4; r_i=r_e//2\n",
    "            c.create_oval(cx-r_e,cy-r_e,cx+r_e,cy+r_e,fill='#606060',outline='')\n",
    "            c.create_oval(cx-r_i,cy-r_i,cx+r_i,cy+r_i,fill='#2A6A2A',outline='')\n",
    "            c.create_oval(cx-r_e,cy-r_e,cx+r_e,cy+r_e,fill='',outline=AMARELO,width=1)\n",
    "        elif icone=='estrada':\n",
    "            c.create_rectangle(0,0,W,H,fill='#3A2A18',outline='')\n",
    "            asf(0,cy-via,W,cy+via)\n",
    "            c.create_line(0,cy,W,cy,fill=BRANCO,width=1,dash=(8,6))\n",
    "        elif icone in ('cruzamento_y','rua_curva'):\n",
    "            cal(0,0,W,H)\n",
    "            asf(0,cy-via,cx+via,cy+via)\n",
    "            asf(cx-via,cy-via,cx+via,H)\n",
    "        else:\n",
    "            c.create_rectangle(0,0,W,H,fill='#0D1830',outline='')\n",
    "            c.create_text(cx,cy,text='Canvas\\nlivre',fill=CINZA_MEDIO,\n",
    "                          font=('Segoe UI',9),justify='center')\n",
]

dest = Path("popups") / "popup_modelo_via.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")