"""
criar_editor_texto.py — Cria widgets/editor_texto.py
Execute com: python criar_editor_texto.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    COR_PAINEL, COR_CARD, AMARELO, BRANCO,\n",
    "    CINZA_CLARO, AZUL_MEDIO,\n",
    "    COR_R1, COR_SUCESSO, COR_PERIGO,\n",
    "    AZUL_CLARO, PRETO_SOFT,\n",
    "    FONTE_PEQ, FONTES_DISPONIVEIS,\n",
    ")\n",
    "\n",
    "\n",
    "class EditorTextoInline:\n",
    "    \"\"\"\n",
    "    Editor de texto inline.\n",
    "    Cria um Entry sobre o canvas na posicao do elemento,\n",
    "    com painel flutuante de formatacao (fonte, tamanho, cor, B/I).\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, janela, canvas, elemento, fn_mt, fn_redesenhar, fn_camadas):\n",
    "        self.janela      = janela\n",
    "        self.canvas      = canvas\n",
    "        self.el          = elemento\n",
    "        self._mt         = fn_mt\n",
    "        self._redesenhar = fn_redesenhar\n",
    "        self._camadas    = fn_camadas\n",
    "        self._ativo      = True\n",
    "\n",
    "        tx, ty = self._mt(elemento.get('x', 0), elemento.get('y', 0))\n",
    "\n",
    "        fonte_nome = elemento.get('fonte', 'Segoe UI')\n",
    "        fonte_tam  = elemento.get('tamanho', 12)\n",
    "        bold_opt   = 'bold' if elemento.get('negrito', False) else 'normal'\n",
    "\n",
    "        self._entry = tk.Entry(canvas,\n",
    "                               font=(fonte_nome, fonte_tam, bold_opt),\n",
    "                               bg='#1A2A4A',\n",
    "                               fg=elemento.get('cor_texto', BRANCO),\n",
    "                               insertbackground=AMARELO,\n",
    "                               relief='flat', bd=2,\n",
    "                               highlightthickness=1,\n",
    "                               highlightcolor=AMARELO,\n",
    "                               highlightbackground=AZUL_MEDIO,\n",
    "                               width=30)\n",
    "        if elemento.get('label'):\n",
    "            self._entry.insert(0, elemento['label'])\n",
    "            self._entry.select_range(0, tk.END)\n",
    "\n",
    "        self._entry_id = canvas.create_window(tx, ty, window=self._entry, anchor='nw')\n",
    "        self._entry.focus_set()\n",
    "        self._entry.bind('<KeyRelease>', self._ao_digitar)\n",
    "        self._entry.bind('<Return>',    self._confirmar)\n",
    "        self._entry.bind('<KP_Enter>',  self._confirmar)\n",
    "        self._entry.bind('<Escape>',    self._cancelar)\n",
    "        self._entry.bind('<FocusOut>',  self._ao_perder_foco)\n",
    "\n",
    "        self._painel = tk.Toplevel(janela)\n",
    "        self._painel.overrideredirect(True)\n",
    "        self._painel.attributes('-topmost', True)\n",
    "        self._painel.configure(bg=COR_PAINEL)\n",
    "        self._painel_build()\n",
    "\n",
    "        canvas.update_idletasks()\n",
    "        px = canvas.winfo_rootx() + tx\n",
    "        py = canvas.winfo_rooty() + ty - 90\n",
    "        if py < 0: py = canvas.winfo_rooty() + ty + 30\n",
    "        self._painel.geometry(f'420x80+{int(px)}+{int(py)}')\n",
    "\n",
    "    def _painel_build(self):\n",
    "        p = self._painel\n",
    "        for w in p.winfo_children(): w.destroy()\n",
    "        tk.Frame(p, bg=AMARELO, height=2).pack(fill='x')\n",
    "        corpo = tk.Frame(p, bg=COR_PAINEL)\n",
    "        corpo.pack(fill='both', expand=True, padx=6, pady=4)\n",
    "\n",
    "        tk.Label(corpo, text='Fonte', font=FONTE_PEQ,\n",
    "                 bg=COR_PAINEL, fg=CINZA_CLARO).grid(row=0, column=0, padx=(0,2))\n",
    "        self._var_fonte = tk.StringVar(value=self.el.get('fonte', 'Segoe UI'))\n",
    "        cb = ttk.Combobox(corpo, textvariable=self._var_fonte,\n",
    "                          values=FONTES_DISPONIVEIS, width=14,\n",
    "                          state='readonly', font=FONTE_PEQ)\n",
    "        cb.grid(row=0, column=1, padx=2)\n",
    "        cb.bind('<<ComboboxSelected>>', self._aplicar_formato)\n",
    "\n",
    "        tk.Label(corpo, text='Tam', font=FONTE_PEQ,\n",
    "                 bg=COR_PAINEL, fg=CINZA_CLARO).grid(row=0, column=2, padx=(6,2))\n",
    "        self._var_tam = tk.IntVar(value=self.el.get('tamanho', 12))\n",
    "        spin = tk.Spinbox(corpo, textvariable=self._var_tam,\n",
    "                          from_=6, to=72, width=4, font=FONTE_PEQ,\n",
    "                          bg=COR_CARD, fg=BRANCO, buttonbackground=COR_CARD,\n",
    "                          relief='flat', command=self._aplicar_formato)\n",
    "        spin.grid(row=0, column=3, padx=2)\n",
    "        spin.bind('<KeyRelease>', self._aplicar_formato)\n",
    "\n",
    "        tk.Label(corpo, text='Cor', font=FONTE_PEQ,\n",
    "                 bg=COR_PAINEL, fg=CINZA_CLARO).grid(row=0, column=4, padx=(6,2))\n",
    "        CORES = [BRANCO, AMARELO, COR_R1, AZUL_CLARO,\n",
    "                 COR_SUCESSO, '#FF8800', '#FF00FF', PRETO_SOFT]\n",
    "        fc = tk.Frame(corpo, bg=COR_PAINEL)\n",
    "        fc.grid(row=0, column=5, padx=2)\n",
    "        for cor in CORES:\n",
    "            tk.Button(fc, bg=cor, width=1, height=1,\n",
    "                      relief='solid', bd=1, cursor='hand2',\n",
    "                      command=lambda c=cor: self._set_cor(c)).pack(side='left', padx=1)\n",
    "\n",
    "        self._var_bold = tk.BooleanVar(value=self.el.get('negrito', False))\n",
    "        self._var_ital = tk.BooleanVar(value=self.el.get('italico', False))\n",
    "        tk.Checkbutton(corpo, text='B', font=('Segoe UI',10,'bold'),\n",
    "                       variable=self._var_bold, bg=COR_PAINEL, fg=BRANCO,\n",
    "                       selectcolor=AZUL_MEDIO, activebackground=COR_PAINEL,\n",
    "                       relief='flat',\n",
    "                       command=self._aplicar_formato).grid(row=0, column=6, padx=2)\n",
    "        tk.Checkbutton(corpo, text='i', font=('Segoe UI',10,'italic'),\n",
    "                       variable=self._var_ital, bg=COR_PAINEL, fg=BRANCO,\n",
    "                       selectcolor=AZUL_MEDIO, activebackground=COR_PAINEL,\n",
    "                       relief='flat',\n",
    "                       command=self._aplicar_formato).grid(row=0, column=7, padx=2)\n",
    "        tk.Button(corpo, text='V', font=('Segoe UI',10,'bold'),\n",
    "                  bg=COR_SUCESSO, fg=PRETO_SOFT,\n",
    "                  relief='flat', cursor='hand2', padx=4,\n",
    "                  command=self._confirmar).grid(row=0, column=8, padx=(8,2))\n",
    "        tk.Button(corpo, text='X', font=('Segoe UI',10),\n",
    "                  bg=COR_PERIGO, fg=BRANCO,\n",
    "                  relief='flat', cursor='hand2', padx=4,\n",
    "                  command=self._cancelar).grid(row=0, column=9, padx=2)\n",
    "        tk.Frame(p, bg=AMARELO, height=2).pack(fill='x', side='bottom')\n",
    "\n",
    "    def _ao_digitar(self, event=None):\n",
    "        self.el['label'] = self._entry.get()\n",
    "        self._redesenhar()\n",
    "\n",
    "    def _set_cor(self, cor):\n",
    "        self._var_cor = cor\n",
    "        self.el['cor_texto'] = cor\n",
    "        self._entry.config(fg=cor)\n",
    "        self._redesenhar()\n",
    "\n",
    "    def _aplicar_formato(self, event=None):\n",
    "        self.el['fonte']   = self._var_fonte.get()\n",
    "        self.el['negrito'] = self._var_bold.get()\n",
    "        self.el['italico'] = self._var_ital.get()\n",
    "        try:\n",
    "            self.el['tamanho'] = max(6, min(72, int(self._var_tam.get())))\n",
    "        except Exception:\n",
    "            pass\n",
    "        bold_opt = 'bold' if self.el['negrito'] else 'normal'\n",
    "        ital_opt = 'italic' if self.el['italico'] else ''\n",
    "        spec = (self.el['fonte'], self.el['tamanho'],\n",
    "                (bold_opt+' '+ital_opt).strip() or 'normal')\n",
    "        self._entry.config(font=spec)\n",
    "        self._redesenhar()\n",
    "\n",
    "    def _confirmar(self, event=None):\n",
    "        if not self._ativo: return\n",
    "        self._ativo = False\n",
    "        self.el['label'] = self._entry.get()\n",
    "        self._aplicar_formato()\n",
    "        self._fechar()\n",
    "        self._camadas()\n",
    "        self._redesenhar()\n",
    "\n",
    "    def _cancelar(self, event=None):\n",
    "        if not self._ativo: return\n",
    "        self._ativo = False\n",
    "        self._fechar()\n",
    "        self._redesenhar()\n",
    "\n",
    "    def _ao_perder_foco(self, event=None):\n",
    "        if self._ativo:\n",
    "            self.janela.after(150, self._verificar_foco)\n",
    "\n",
    "    def _verificar_foco(self):\n",
    "        if not self._ativo: return\n",
    "        try:\n",
    "            foco = self.janela.focus_get()\n",
    "            if self._painel.winfo_exists():\n",
    "                if foco and str(foco).startswith(str(self._painel)):\n",
    "                    return\n",
    "        except Exception:\n",
    "            pass\n",
    "        self._confirmar()\n",
    "\n",
    "    def _fechar(self):\n",
    "        try:\n",
    "            self.canvas.delete(self._entry_id)\n",
    "            self._entry.destroy()\n",
    "        except Exception:\n",
    "            pass\n",
    "        try:\n",
    "            if self._painel.winfo_exists():\n",
    "                self._painel.destroy()\n",
    "        except Exception:\n",
    "            pass\n",
]

dest = Path("widgets") / "editor_texto.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")