"""
criar_splash_v4.py — Splash minima: so barra + status sobre splash_bg.png
Execute: python criar_splash_v4.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "from tema import (\n",
    "    FUNDO_BASE, DOURADO, AZUL_BORDA,\n",
    "    TEXTO_TERCIARIO,\n",
    "    SPLASH_W, SPLASH_H, SPLASH_DURACAO, SPLASH_MSGS,\n",
    ")\n",
    "\n",
    "\n",
    "class SplashScreen(tk.Toplevel):\n",
    "    def __init__(self, parent, img_brasao=None):\n",
    "        super().__init__(parent)\n",
    "        self.overrideredirect(True)\n",
    "        parent.withdraw()\n",
    "        parent.wm_attributes('-alpha', 0)\n",
    "        W, H = SPLASH_W, SPLASH_H\n",
    "        sw = self.winfo_screenwidth()\n",
    "        sh = self.winfo_screenheight()\n",
    "        self.geometry(f'{W}x{H}+{(sw-W)//2}+{(sh-H)//2}')\n",
    "        self.configure(bg=FUNDO_BASE)\n",
    "        self.lift()\n",
    "        self.attributes('-topmost', True)\n",
    "        self._W = W; self._H = H\n",
    "        self._p = 0.0\n",
    "        self._build()\n",
    "        self._anim()\n",
    "\n",
    "    def _build(self):\n",
    "        W, H = self._W, self._H\n",
    "        self.cv = tk.Canvas(self, width=W, height=H,\n",
    "                            bg=FUNDO_BASE, highlightthickness=0)\n",
    "        self.cv.place(x=0, y=0, width=W, height=H)\n",
    "\n",
    "        # Carrega splash_bg.png — ela tem todo o visual\n",
    "        bg_path = Path(__file__).parent.parent / 'assets' / 'splash_bg.png'\n",
    "        self._bg_tk = None\n",
    "        if PIL_OK and bg_path.exists():\n",
    "            try:\n",
    "                bg = Image.open(bg_path).resize((W, H), Image.LANCZOS)\n",
    "                self._bg_tk = ImageTk.PhotoImage(bg)\n",
    "                self.cv.create_image(0, 0, anchor='nw', image=self._bg_tk)\n",
    "            except Exception:\n",
    "                self.cv.create_rectangle(0, 0, W, H, fill=FUNDO_BASE, outline='')\n",
    "        else:\n",
    "            # Fallback minimo se nao houver imagem\n",
    "            self.cv.create_rectangle(0, 0, W, H, fill=FUNDO_BASE, outline='')\n",
    "            self.cv.create_text(W//2, H//2, text='SICRO',\n",
    "                                font=('Segoe UI', 44, 'bold'),\n",
    "                                fill='#E8EDF5', anchor='center')\n",
    "\n",
    "        # Barra de progresso — unico elemento programatico\n",
    "        # Posicao: 77.5% da altura, 20% de margem lateral\n",
    "        bx = int(W * 0.12)\n",
    "        bw = W - bx * 2\n",
    "        by = int(H * 0.775)\n",
    "        bh = 4\n",
    "\n",
    "        # Trilho\n",
    "        self.cv.create_rectangle(bx, by, bx+bw, by+bh,\n",
    "                                 fill='#1A2A4A', outline='')\n",
    "        # Preenchimento\n",
    "        self._barra = self.cv.create_rectangle(\n",
    "            bx, by, bx, by+bh,\n",
    "            fill=DOURADO, outline='')\n",
    "\n",
    "        self._bx = bx; self._bw = bw\n",
    "        self._by = by; self._bh = bh\n",
    "\n",
    "        # Texto de status — unico texto programatico\n",
    "        self._status = self.cv.create_text(\n",
    "            W//2, int(H * 0.838),\n",
    "            text='Inicializando...',\n",
    "            font=('Segoe UI', 9),\n",
    "            fill=TEXTO_TERCIARIO,\n",
    "            anchor='center')\n",
    "\n",
    "    def _anim(self):\n",
    "        if self._p >= 100: return\n",
    "        self._p = min(100.0, self._p + 100 / (SPLASH_DURACAO / 50))\n",
    "        larg = int(self._bw * self._p / 100)\n",
    "        self.cv.coords(self._barra,\n",
    "                       self._bx, self._by,\n",
    "                       self._bx + larg, self._by + self._bh)\n",
    "        msg = SPLASH_MSGS[0][1]\n",
    "        for pct, txt in SPLASH_MSGS:\n",
    "            if self._p >= pct: msg = txt\n",
    "        self.cv.itemconfig(self._status, text=msg)\n",
    "        self.after(50, self._anim)\n",
    "\n",
    "    def fechar(self):\n",
    "        try:\n",
    "            self.master.wm_attributes('-alpha', 1)\n",
    "        except Exception:\n",
    "            pass\n",
    "        self.destroy()\n",
]

dest = Path("ui") / "splash.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} ({len(linhas)} linhas)")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")
print("Rode: python main.py")