"""
criar_painel_camadas.py — Cria widgets/painel_camadas.py
Execute com: python criar_painel_camadas.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    COR_PAINEL, COR_CARD, AMARELO, BRANCO,\n",
    "    CINZA_MEDIO, CINZA_CLARO, AZUL_MEDIO,\n",
    "    FONTE_SUB, FONTE_PEQ,\n",
    "    TIPO_INFO,\n",
    ")\n",
    "\n",
    "\n",
    "class PainelCamadas:\n",
    "    \"\"\"\n",
    "    Painel lateral de camadas.\n",
    "    Construido dentro de um frame pai (pd).\n",
    "    Recebe callbacks do EditorCroqui via construtor.\n",
    "\n",
    "    Callbacks esperados:\n",
    "      on_selecionar(el_idx)  — chamado ao clicar numa camada\n",
    "      on_subir()             — move elemento selecionado para cima\n",
    "      on_descer()            — move elemento selecionado para baixo\n",
    "      on_apagar()            — apaga elemento selecionado\n",
    "      get_elementos()        — retorna lista atual de elementos\n",
    "      get_sel_idx()          — retorna indice selecionado atual\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, pd, status_bar,\n",
    "                 on_selecionar, on_subir, on_descer, on_apagar,\n",
    "                 get_elementos, get_sel_idx):\n",
    "        self.status      = status_bar\n",
    "        self.on_sel      = on_selecionar\n",
    "        self.on_subir    = on_subir\n",
    "        self.on_descer   = on_descer\n",
    "        self.on_apagar   = on_apagar\n",
    "        self.get_els     = get_elementos\n",
    "        self.get_sel_idx = get_sel_idx\n",
    "\n",
    "        tk.Frame(pd, bg=AMARELO, height=2).pack(fill='x')\n",
    "\n",
    "        # Cabecalho com botoes de ordem\n",
    "        cab = tk.Frame(pd, bg=COR_PAINEL)\n",
    "        cab.pack(fill='x', padx=6, pady=(8,2))\n",
    "        tk.Label(cab, text='Camadas', font=FONTE_SUB,\n",
    "                 bg=COR_PAINEL, fg=AMARELO).pack(side='left')\n",
    "        for sym, tip, cmd in [\n",
    "            ('▲', 'Subir camada',  self._subir),\n",
    "            ('▼', 'Descer camada', self._descer),\n",
    "        ]:\n",
    "            b = tk.Button(cab, text=sym, font=('Segoe UI',9),\n",
    "                          width=2, cursor='hand2',\n",
    "                          bg=COR_CARD, fg=BRANCO,\n",
    "                          activebackground=AZUL_MEDIO,\n",
    "                          relief='flat', pady=1,\n",
    "                          command=cmd)\n",
    "            b.pack(side='right', padx=1)\n",
    "            b.bind('<Enter>', lambda e, t=tip: self.status.config(text=t))\n",
    "\n",
    "        # Listbox\n",
    "        flb = tk.Frame(pd, bg=COR_CARD)\n",
    "        flb.pack(fill='both', expand=True, padx=4, pady=2)\n",
    "        scrl = tk.Scrollbar(flb)\n",
    "        scrl.pack(side='right', fill='y')\n",
    "        self.lb = tk.Listbox(\n",
    "            flb,\n",
    "            yscrollcommand=scrl.set,\n",
    "            bg=COR_CARD, fg=BRANCO,\n",
    "            selectbackground=AZUL_MEDIO,\n",
    "            selectforeground=BRANCO,\n",
    "            font=('Segoe UI', 9),\n",
    "            relief='flat', bd=0,\n",
    "            activestyle='none',\n",
    "            highlightthickness=0,\n",
    "        )\n",
    "        self.lb.pack(fill='both', expand=True)\n",
    "        scrl.config(command=self.lb.yview)\n",
    "        self.lb.bind('<<ListboxSelect>>', self._selecionada)\n",
    "\n",
    "        # Botao apagar\n",
    "        tk.Button(pd, text='Apagar selecionado',\n",
    "                  font=FONTE_PEQ, cursor='hand2',\n",
    "                  bg='#3A1010', fg='#FF8080',\n",
    "                  activebackground='#5A1A1A',\n",
    "                  relief='flat', pady=4,\n",
    "                  command=self._apagar).pack(fill='x', padx=4, pady=(0,4))\n",
    "\n",
    "    def atualizar(self):\n",
    "        \"\"\"Sincroniza o Listbox com a lista de elementos atual.\"\"\"\n",
    "        elementos = self.get_els()\n",
    "        sel_atual = self.get_sel_idx()\n",
    "        self.lb.delete(0, tk.END)\n",
    "        for i, el in reversed(list(enumerate(elementos))):\n",
    "            icone, nome = TIPO_INFO.get(el['tipo'], ('?', el['tipo']))\n",
    "            label_el = el.get('label', '')\n",
    "            txt = f' {icone}  {nome}'\n",
    "            if label_el:\n",
    "                txt += f'  [{label_el}]'\n",
    "            self.lb.insert(tk.END, txt)\n",
    "            if el['tipo'].startswith('_'):\n",
    "                self.lb.itemconfig(tk.END, fg=CINZA_MEDIO)\n",
    "            else:\n",
    "                self.lb.itemconfig(tk.END, fg=BRANCO)\n",
    "        if sel_atual is not None:\n",
    "            lb_idx = len(elementos) - 1 - sel_atual\n",
    "            if 0 <= lb_idx < self.lb.size():\n",
    "                self.lb.selection_set(lb_idx)\n",
    "                self.lb.see(lb_idx)\n",
    "\n",
    "    def _selecionada(self, event=None):\n",
    "        sel = self.lb.curselection()\n",
    "        if not sel: return\n",
    "        lb_idx = sel[0]\n",
    "        elementos = self.get_els()\n",
    "        el_idx = len(elementos) - 1 - lb_idx\n",
    "        if 0 <= el_idx < len(elementos):\n",
    "            self.on_sel(el_idx)\n",
    "\n",
    "    def _subir(self):   self.on_subir()\n",
    "    def _descer(self):  self.on_descer()\n",
    "    def _apagar(self):  self.on_apagar()\n",
]

dest = Path("widgets") / "painel_camadas.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")