"""
criar_splash_v3.py — Splash minimalista premium
Execute: python criar_splash_v3.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "from tema import (\n",
    "    FUNDO_BASE, FUNDO_PAINEL,\n",
    "    DOURADO, AZUL_BORDA, AZUL_MEDIO,\n",
    "    TEXTO_PRIMARIO, TEXTO_SECUNDARIO, TEXTO_TERCIARIO,\n",
    "    SPLASH_W, SPLASH_H, SPLASH_DURACAO, SPLASH_MSGS,\n",
    ")\n",
    "\n",
    "\n",
    "class SplashScreen(tk.Toplevel):\n",
    "    def __init__(self, parent, img_brasao=None):\n",
    "        super().__init__(parent)\n",
    "        # Remove moldura Windows completamente\n",
    "        self.overrideredirect(True)\n",
    "        # Esconde a janela pai da barra de tarefas durante a splash\n",
    "        parent.withdraw()\n",
    "        parent.wm_attributes('-alpha', 0)\n",
    "        W, H = SPLASH_W, SPLASH_H\n",
    "        sw = self.winfo_screenwidth()\n",
    "        sh = self.winfo_screenheight()\n",
    "        self.geometry(f'{W}x{H}+{(sw-W)//2}+{(sh-H)//2}')\n",
    "        self.configure(bg=FUNDO_BASE)\n",
    "        self.lift()\n",
    "        self.attributes('-topmost', True)\n",
    "        self._W = W; self._H = H\n",
    "        self._p = 0.0\n",
    "        self._build(img_brasao)\n",
    "        self._anim()\n",
    "\n",
    "    def _build(self, img_brasao):\n",
    "        W, H = self._W, self._H\n",
    "        self.cv = tk.Canvas(self, width=W, height=H,\n",
    "                            bg=FUNDO_BASE, highlightthickness=0)\n",
    "        self.cv.place(x=0, y=0, width=W, height=H)\n",
    "        bg_path = Path(__file__).parent.parent / 'assets' / 'splash_bg.png'\n",
    "        self._bg_tk = None\n",
    "        if PIL_OK and bg_path.exists():\n",
    "            try:\n",
    "                bg = Image.open(bg_path).resize((W, H), Image.LANCZOS)\n",
    "                self._bg_tk = ImageTk.PhotoImage(bg)\n",
    "                self.cv.create_image(0, 0, anchor='nw', image=self._bg_tk)\n",
    "                self.cv.create_rectangle(0, 0, W, H,\n",
    "                                         fill=FUNDO_BASE, stipple='gray50', outline='')\n",
    "            except Exception:\n",
    "                self._fundo_programatico()\n",
    "        else:\n",
    "            self._fundo_programatico()\n",
    "        # Borda sutil\n",
    "        self.cv.create_rectangle(1, 1, W-2, H-2,\n",
    "                                 outline=AZUL_BORDA, fill='', width=1)\n",
    "        # Faixa dourada topo\n",
    "        self.cv.create_rectangle(0, 0, W, 4, fill=DOURADO, outline='')\n",
    "        # Icone\n",
    "        cy_icon = int(H * 0.32)\n",
    "        if img_brasao and PIL_OK:\n",
    "            try:\n",
    "                img = img_brasao.resize((72, 72), Image.LANCZOS)\n",
    "                self._logo_tk = ImageTk.PhotoImage(img)\n",
    "                self.cv.create_image(W//2, cy_icon, anchor='center', image=self._logo_tk)\n",
    "            except Exception:\n",
    "                self._icone_mira(W//2, cy_icon)\n",
    "        else:\n",
    "            self._icone_mira(W//2, cy_icon)\n",
    "        # Nome\n",
    "        self.cv.create_text(W//2, int(H*0.515),\n",
    "                            text='SICRO', font=('Segoe UI', 44, 'bold'),\n",
    "                            fill=TEXTO_PRIMARIO, anchor='center')\n",
    "        # Subtitulo — uma linha\n",
    "        self.cv.create_text(W//2, int(H*0.608),\n",
    "                            text='Sistema de Croquis e Reconstrucao de Ocorrencias',\n",
    "                            font=('Segoe UI', 10),\n",
    "                            fill=TEXTO_SECUNDARIO, anchor='center')\n",
    "        # Linha divisoria\n",
    "        mx = int(W * 0.35)\n",
    "        self.cv.create_line(mx, int(H*0.688), W-mx, int(H*0.688),\n",
    "                            fill=AZUL_BORDA, width=1)\n",
    "        # Barra de progresso (canvas puro — sem widget)\n",
    "        bx = int(W * 0.20); bw = W - bx * 2\n",
    "        by = int(H * 0.775); bh = 3\n",
    "        self.cv.create_rectangle(bx, by, bx+bw, by+bh,\n",
    "                                 fill='#1A2A4A', outline='')\n",
    "        self._barra = self.cv.create_rectangle(\n",
    "            bx, by, bx, by+bh, fill=DOURADO, outline='')\n",
    "        self._bx=bx; self._bw=bw; self._by=by; self._bh=bh\n",
    "        # Status\n",
    "        self._status = self.cv.create_text(\n",
    "            W//2, int(H*0.845), text='Inicializando...',\n",
    "            font=('Segoe UI', 9), fill=TEXTO_TERCIARIO, anchor='center')\n",
    "        # Rodape\n",
    "        self.cv.create_text(W//2, int(H*0.936),\n",
    "                            text='Policia Cientifica do Amapa',\n",
    "                            font=('Segoe UI', 8),\n",
    "                            fill=TEXTO_TERCIARIO, anchor='center')\n",
    "        self.cv.create_text(W-16, H-12, text='v1.0.0-alpha',\n",
    "                            font=('Segoe UI', 8),\n",
    "                            fill=TEXTO_TERCIARIO, anchor='se')\n",
    "        # Faixa dourada base\n",
    "        self.cv.create_rectangle(0, H-4, W, H, fill=DOURADO, outline='')\n",
    "\n",
    "    def _fundo_programatico(self):\n",
    "        W, H = self._W, self._H; c = self.cv\n",
    "        c.create_rectangle(0, 0, W, H, fill='#0D1830', outline='')\n",
    "        c.create_rectangle(0, H*0.6, W, H, fill='#0A1020', outline='')\n",
    "        for x in range(0, W, 60):\n",
    "            c.create_line(x, 0, x, H, fill='#0F1E35', width=1)\n",
    "        for y in range(0, H, 60):\n",
    "            c.create_line(0, y, W, y, fill='#0F1E35', width=1)\n",
    "\n",
    "    def _icone_mira(self, cx, cy):\n",
    "        c = self.cv; r = 28; gap = 10\n",
    "        pts = [cx, cy-r, cx+r*0.72, cy, cx, cy+r, cx-r*0.72, cy]\n",
    "        c.create_polygon(pts, fill='', outline=DOURADO, width=1.5)\n",
    "        for p in [(cx-r*0.6,cy,cx-gap,cy),(cx+gap,cy,cx+r*0.6,cy),\n",
    "                  (cx,cy-r*0.6,cx,cy-gap),(cx,cy+gap,cx,cy+r*0.6)]:\n",
    "            c.create_line(*p, fill=TEXTO_PRIMARIO, width=1)\n",
    "        c.create_oval(cx-8,cy-8,cx+8,cy+8, fill='',outline=AZUL_MEDIO,width=1.5)\n",
    "        c.create_oval(cx-3,cy-3,cx+3,cy+3, fill=DOURADO,outline='')\n",
    "\n",
    "    def _anim(self):\n",
    "        if self._p >= 100: return\n",
    "        self._p = min(100.0, self._p + 100/(SPLASH_DURACAO/50))\n",
    "        larg = int(self._bw * self._p / 100)\n",
    "        self.cv.coords(self._barra,\n",
    "                       self._bx, self._by,\n",
    "                       self._bx+larg, self._by+self._bh)\n",
    "        msg = SPLASH_MSGS[0][1]\n",
    "        for pct, txt in SPLASH_MSGS:\n",
    "            if self._p >= pct: msg = txt\n",
    "        self.cv.itemconfig(self._status, text=msg)\n",
    "        self.after(50, self._anim)\n",
    "\n",
    "    def fechar(self):\n",
    "        # Restaura alpha da janela pai antes de fechar\n",
    "        try:\n",
    "            self.master.wm_attributes('-alpha', 1)\n",
    "        except Exception:\n",
    "            pass\n",
    "        self.destroy()\n",
]

dest = Path("ui") / "splash.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} ({len(linhas)} linhas)")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")
print("Rode: python main.py")