"""
criar_tela_inicial_v3.py — Tela inicial v3
Cores ajustadas + imagens nos cards
Execute: python criar_tela_inicial_v3.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import datetime, json, sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "from tema import (\n",
    "    FUNDO_BASE, FUNDO_PAINEL, FUNDO_CARD, FUNDO_HOVER,\n",
    "    FUNDO_ATIVO, AZUL_BORDA, AZUL_MEDIO,\n",
    "    DOURADO, TEXTO_PRIMARIO, TEXTO_SECUNDARIO, TEXTO_TERCIARIO,\n",
    "    TEXTO_INVERTIDO, COR_SUCESSO,\n",
    "    FONTE_H1, FONTE_H2, FONTE_H3, FONTE_BODY, FONTE_BODY_BOLD,\n",
    "    FONTE_SMALL, FONTE_SMALL_BOLD, FONTE_MICRO,\n",
    "    LARGURA_SIDEBAR_INICIO, ALTURA_HEADER, ALTURA_BARRA_TOP,\n",
    "    SIDEBAR_ITENS,\n",
    ")\n",
    "from config import DIR_CROQUIS\n",
    "\n",
    "# Assets dos cards\n",
    "_CARD_IMGS = {\n",
    "    'zero':   'card_manual.png',\n",
    "    'drone':  'card_drone.png',\n",
    "    'modelo': 'card_modelo.png',\n",
    "}\n",
    "_card_tk_cache = {}\n",
    "\n",
    "def _carregar_card_img(chave, w, h):\n",
    "    if not PIL_OK: return None\n",
    "    key = (chave, w, h)\n",
    "    if key in _card_tk_cache: return _card_tk_cache[key]\n",
    "    path = Path(__file__).parent.parent / 'assets' / _CARD_IMGS[chave]\n",
    "    if not path.exists(): return None\n",
    "    try:\n",
    "        img = Image.open(path).convert('RGBA').resize((w, h), Image.LANCZOS)\n",
    "        # Escurece levemente para o texto ficar legivel\n",
    "        from PIL import ImageEnhance\n",
    "        img = ImageEnhance.Brightness(img).enhance(0.55)\n",
    "        tk_img = ImageTk.PhotoImage(img)\n",
    "        _card_tk_cache[key] = tk_img\n",
    "        return tk_img\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "\n",
    "class TelaInicial(tk.Frame):\n",
    "    def __init__(self, master, on_novo, on_abrir, img_brasao=None):\n",
    "        super().__init__(master, bg=FUNDO_BASE)\n",
    "        self.on_novo    = on_novo\n",
    "        self.on_abrir   = on_abrir\n",
    "        self.img_brasao = img_brasao\n",
    "        self._aba_ativa = 'inicio'\n",
    "        self._build()\n",
    "\n",
    "    def _build(self):\n",
    "        tk.Frame(self, bg=DOURADO, height=ALTURA_BARRA_TOP).pack(fill='x')\n",
    "        self._build_header()\n",
    "        corpo = tk.Frame(self, bg=FUNDO_BASE)\n",
    "        corpo.pack(fill='both', expand=True)\n",
    "        self._build_sidebar(corpo)\n",
    "        self._area = tk.Frame(corpo, bg=FUNDO_BASE)\n",
    "        self._area.pack(side='left', fill='both', expand=True)\n",
    "        self._mostrar_inicio()\n",
    "\n",
    "    def _build_header(self):\n",
    "        h = tk.Frame(self, bg=FUNDO_PAINEL, height=ALTURA_HEADER)\n",
    "        h.pack(fill='x'); h.pack_propagate(False)\n",
    "        esq = tk.Frame(h, bg=FUNDO_PAINEL)\n",
    "        esq.pack(side='left', padx=16, pady=0, fill='y')\n",
    "        if self.img_brasao and PIL_OK:\n",
    "            try:\n",
    "                img = self.img_brasao.resize((28, 28), Image.LANCZOS)\n",
    "                self._hdr_tk = ImageTk.PhotoImage(img)\n",
    "                tk.Label(esq, image=self._hdr_tk,\n",
    "                         bg=FUNDO_PAINEL).pack(side='left', padx=(0,8))\n",
    "            except Exception: pass\n",
    "        tk.Label(esq, text='SICRO', font=FONTE_H2,\n",
    "                 bg=FUNDO_PAINEL, fg=TEXTO_PRIMARIO).pack(side='left')\n",
    "        tk.Label(esq, text='  Sistema de Croquis Periciais',\n",
    "                 font=FONTE_SMALL, bg=FUNDO_PAINEL,\n",
    "                 fg=TEXTO_TERCIARIO).pack(side='left')\n",
    "        dir_ = tk.Frame(h, bg=FUNDO_PAINEL)\n",
    "        dir_.pack(side='right', padx=16, fill='y')\n",
    "        tk.Label(dir_,\n",
    "                 text=f'Policia Cientifica do Amapa  |  '\n",
    "                      f'{datetime.date.today().strftime(\"%d/%m/%Y\")}',\n",
    "                 font=FONTE_MICRO, bg=FUNDO_PAINEL,\n",
    "                 fg=TEXTO_TERCIARIO).pack(expand=True)\n",
    "\n",
    "    def _build_sidebar(self, parent):\n",
    "        sb = tk.Frame(parent, bg=FUNDO_PAINEL,\n",
    "                      width=LARGURA_SIDEBAR_INICIO)\n",
    "        sb.pack(side='left', fill='y')\n",
    "        sb.pack_propagate(False)\n",
    "        # Borda direita\n",
    "        tk.Frame(sb, bg=AZUL_BORDA, width=1).pack(side='right', fill='y')\n",
    "        inner = tk.Frame(sb, bg=FUNDO_PAINEL)\n",
    "        inner.pack(fill='both', expand=True)\n",
    "        tk.Frame(inner, bg=FUNDO_PAINEL, height=16).pack()\n",
    "        self._sb_btns = {}\n",
    "        for chave, icone, label in SIDEBAR_ITENS:\n",
    "            if chave == 'sep':\n",
    "                tk.Frame(inner, bg=AZUL_BORDA, height=1).pack(\n",
    "                    fill='x', padx=16, pady=8)\n",
    "                continue\n",
    "            ativo = (chave == self._aba_ativa)\n",
    "            self._sb_btns[chave] = self._sb_btn(\n",
    "                inner, icone, label, chave, ativo)\n",
    "        # Rodape\n",
    "        rod = tk.Frame(sb, bg=FUNDO_PAINEL)\n",
    "        rod.pack(side='bottom', pady=14)\n",
    "        tk.Label(rod, text='PCI/AP', font=FONTE_SMALL_BOLD,\n",
    "                 bg=FUNDO_PAINEL, fg=DOURADO).pack()\n",
    "        tk.Label(rod, text='v1.0.0-alpha', font=FONTE_MICRO,\n",
    "                 bg=FUNDO_PAINEL, fg=TEXTO_TERCIARIO).pack()\n",
    "\n",
    "    def _sb_btn(self, parent, icone, label, chave, ativo=False):\n",
    "        bg_n  = FUNDO_ATIVO if ativo else FUNDO_PAINEL\n",
    "        f = tk.Frame(parent, bg=bg_n, cursor='hand2')\n",
    "        f.pack(fill='x', pady=1)\n",
    "        ind = tk.Frame(f, bg=DOURADO if ativo else bg_n, width=3)\n",
    "        ind.pack(side='left', fill='y')\n",
    "        tk.Label(f, text=icone, font=('Segoe UI', 13),\n",
    "                 bg=bg_n,\n",
    "                 fg=DOURADO if ativo else TEXTO_SECUNDARIO,\n",
    "                 width=2).pack(side='left', padx=(10,4), pady=10)\n",
    "        tk.Label(f, text=label,\n",
    "                 font=FONTE_SMALL_BOLD if ativo else FONTE_SMALL,\n",
    "                 bg=bg_n,\n",
    "                 fg=TEXTO_PRIMARIO if ativo else TEXTO_SECUNDARIO,\n",
    "                 anchor='w').pack(side='left', fill='x', expand=True)\n",
    "        def _hin(e, fr=f, at=ativo):\n",
    "            if not at:\n",
    "                fr.config(bg=FUNDO_HOVER)\n",
    "                for w in fr.winfo_children(): w.config(bg=FUNDO_HOVER)\n",
    "        def _hout(e, fr=f, at=ativo):\n",
    "            if not at:\n",
    "                fr.config(bg=FUNDO_PAINEL)\n",
    "                for w in fr.winfo_children(): w.config(bg=FUNDO_PAINEL)\n",
    "        def _click(e, ch=chave): self._navegar(ch)\n",
    "        for w in [f] + list(f.winfo_children()):\n",
    "            w.bind('<Enter>', _hin)\n",
    "            w.bind('<Leave>', _hout)\n",
    "            w.bind('<Button-1>', _click)\n",
    "        return f\n",
    "\n",
    "    def _navegar(self, chave):\n",
    "        self._aba_ativa = chave\n",
    "        for w in self._area.winfo_children(): w.destroy()\n",
    "        if chave == 'inicio':   self._mostrar_inicio()\n",
    "        elif chave == 'recentes': self._mostrar_recentes()\n",
    "        else:\n",
    "            tk.Label(self._area,\n",
    "                     text=f'Em construcao: {chave}',\n",
    "                     font=FONTE_H2, bg=FUNDO_BASE,\n",
    "                     fg=TEXTO_TERCIARIO).pack(expand=True)\n",
    "\n",
    "    def _mostrar_inicio(self):\n",
    "        a = self._area\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=28).pack()\n",
    "        tk.Label(a, text='Bem-vindo ao SICRO',\n",
    "                 font=FONTE_H1, bg=FUNDO_BASE,\n",
    "                 fg=TEXTO_PRIMARIO).pack(anchor='w', padx=32)\n",
    "        tk.Label(a, text='Escolha como deseja iniciar o seu croqui.',\n",
    "                 font=FONTE_SMALL, bg=FUNDO_BASE,\n",
    "                 fg=TEXTO_SECUNDARIO).pack(anchor='w', padx=32)\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=20).pack()\n",
    "        # Cards\n",
    "        cf = tk.Frame(a, bg=FUNDO_BASE)\n",
    "        cf.pack(fill='x', padx=32)\n",
    "        acoes = [\n",
    "            ('Novo Croqui Manual',\n",
    "             'Comece um croqui do zero\\nem uma tela vazia.',\n",
    "             AZUL_MEDIO, 'zero',\n",
    "             lambda: self.on_novo('zero')),\n",
    "            ('Croqui com Drone',\n",
    "             'Importe imagens aereas\\ne crie seu croqui.',\n",
    "             '#1A5A3A', 'drone',\n",
    "             lambda: self.on_novo('drone')),\n",
    "            ('Usar Modelo Pronto',\n",
    "             'Escolha um modelo de via\\ne comece rapidamente.',\n",
    "             DOURADO, 'modelo',\n",
    "             lambda: self.on_novo('modelo')),\n",
    "        ]\n",
    "        for titulo, desc, cor, img_chave, cmd in acoes:\n",
    "            self._card_acao(cf, titulo, desc, cor, img_chave, cmd)\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=28).pack()\n",
    "        # Recentes\n",
    "        rh = tk.Frame(a, bg=FUNDO_BASE)\n",
    "        rh.pack(fill='x', padx=32)\n",
    "        tk.Label(rh, text='Croquis recentes',\n",
    "                 font=FONTE_H3, bg=FUNDO_BASE,\n",
    "                 fg=TEXTO_PRIMARIO).pack(side='left')\n",
    "        tk.Button(rh, text='Ver todos >',\n",
    "                  font=FONTE_MICRO, cursor='hand2',\n",
    "                  bg=FUNDO_BASE, fg=DOURADO,\n",
    "                  activebackground=FUNDO_BASE,\n",
    "                  relief='flat', bd=0,\n",
    "                  command=lambda: self._navegar('recentes')).pack(side='right')\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=10).pack()\n",
    "        self._lista_recentes(a, limite=5)\n",
    "        # Rodape\n",
    "        rod = tk.Frame(a, bg=FUNDO_BASE)\n",
    "        rod.pack(fill='x', padx=32, pady=16, side='bottom')\n",
    "        tk.Button(rod, text='  Abrir croqui existente...',\n",
    "                  font=FONTE_SMALL_BOLD, cursor='hand2',\n",
    "                  bg=FUNDO_CARD, fg=TEXTO_PRIMARIO,\n",
    "                  activebackground=FUNDO_HOVER,\n",
    "                  relief='flat', bd=0, padx=16, pady=8,\n",
    "                  command=self._abrir_sel).pack(side='left')\n",
    "\n",
    "    def _card_acao(self, parent, titulo, desc, cor_acento, img_chave, cmd):\n",
    "        IMG_H = 140\n",
    "        card = tk.Frame(parent, bg=FUNDO_CARD, cursor='hand2')\n",
    "        card.pack(side='left', fill='both', expand=True, padx=(0,12))\n",
    "        # Imagem de fundo — usa Canvas para controlar altura\n",
    "        img_canvas = tk.Canvas(card, height=IMG_H, bg=FUNDO_CARD,\n",
    "                              highlightthickness=0)\n",
    "        img_canvas.pack(fill='x')\n",
    "        def _draw_img(event, ic=img_canvas, ck=img_chave, ih=IMG_H, ca=cor_acento):\n",
    "            w = ic.winfo_width()\n",
    "            if w < 2: return\n",
    "            tk_img = _carregar_card_img(ck, w, ih)\n",
    "            ic.delete('all')\n",
    "            if tk_img:\n",
    "                ic._img = tk_img\n",
    "                ic.create_image(0, 0, anchor='nw', image=tk_img)\n",
    "            else:\n",
    "                ic.create_rectangle(0, 0, w, ih, fill=ca, outline='')\n",
    "        img_canvas.bind('<Configure>', _draw_img)\n",
    "        # Faixa colorida separadora\n",
    "        tk.Frame(card, bg=cor_acento, height=2).pack(fill='x')\n",
    "        # Conteudo\n",
    "        inner = tk.Frame(card, bg=FUNDO_CARD)\n",
    "        inner.pack(fill='both', expand=True, padx=14, pady=12)\n",
    "        tk.Label(inner, text=titulo, font=FONTE_BODY_BOLD,\n",
    "                 bg=FUNDO_CARD, fg=TEXTO_PRIMARIO, anchor='w').pack(fill='x')\n",
    "        tk.Label(inner, text=desc, font=FONTE_SMALL,\n",
    "                 bg=FUNDO_CARD, fg=TEXTO_SECUNDARIO,\n",
    "                 justify='left', anchor='w').pack(fill='x', pady=(4,10))\n",
    "        btn_fg = TEXTO_INVERTIDO if cor_acento == DOURADO else TEXTO_PRIMARIO\n",
    "        tk.Button(inner, text='Iniciar  >',\n",
    "                  font=FONTE_SMALL_BOLD, cursor='hand2',\n",
    "                  bg=cor_acento, fg=btn_fg,\n",
    "                  activebackground=FUNDO_HOVER,\n",
    "                  relief='flat', bd=0, padx=12, pady=5,\n",
    "                  command=cmd).pack(anchor='w')\n",
    "        # Hover\n",
    "        def _hin(e):\n",
    "            card.config(bg=FUNDO_HOVER); inner.config(bg=FUNDO_HOVER)\n",
    "            for w in inner.winfo_children():\n",
    "                try: w.config(bg=FUNDO_HOVER)\n",
    "                except Exception: pass\n",
    "        def _hout(e):\n",
    "            card.config(bg=FUNDO_CARD); inner.config(bg=FUNDO_CARD)\n",
    "            for w in inner.winfo_children():\n",
    "                try: w.config(bg=FUNDO_CARD)\n",
    "                except Exception: pass\n",
    "        card.bind('<Enter>', _hin); card.bind('<Leave>', _hout)\n",
    "        inner.bind('<Enter>', _hin); inner.bind('<Leave>', _hout)\n",
    "\n",
    "    def _mostrar_recentes(self):\n",
    "        a = self._area\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=28).pack()\n",
    "        tk.Label(a, text='Croquis recentes',\n",
    "                 font=FONTE_H1, bg=FUNDO_BASE,\n",
    "                 fg=TEXTO_PRIMARIO).pack(anchor='w', padx=32)\n",
    "        tk.Frame(a, bg=FUNDO_BASE, height=14).pack()\n",
    "        self._lista_recentes(a, limite=50)\n",
    "\n",
    "    def _lista_recentes(self, parent, limite=5):\n",
    "        arqs = sorted(DIR_CROQUIS.glob('*.sicro'), reverse=True)[:limite]\n",
    "        self._arqs_recentes = list(arqs)\n",
    "        if not arqs:\n",
    "            tk.Label(parent,\n",
    "                     text='Nenhum croqui salvo ainda.',\n",
    "                     font=FONTE_SMALL, bg=FUNDO_BASE,\n",
    "                     fg=TEXTO_TERCIARIO).pack(padx=32, anchor='w')\n",
    "            return\n",
    "        for i, arq in enumerate(arqs):\n",
    "            self._item_recente(parent, arq)\n",
    "\n",
    "    def _item_recente(self, parent, arq):\n",
    "        try:\n",
    "            with open(arq) as f: d = json.load(f)\n",
    "        except Exception: d = {}\n",
    "        bo    = d.get('bo', '?')\n",
    "        local = d.get('local', arq.stem)[:50]\n",
    "        data  = d.get('data', '')\n",
    "        modo  = d.get('modo', 'zero')\n",
    "        tag_cor = AZUL_MEDIO if modo == 'zero' else '#1A5A3A'\n",
    "        tag_txt = 'Manual' if modo == 'zero' else 'Drone'\n",
    "        row = tk.Frame(parent, bg=FUNDO_CARD, cursor='hand2')\n",
    "        row.pack(fill='x', padx=32, pady=2)\n",
    "        tk.Frame(row, bg=AZUL_BORDA, width=3).pack(side='left', fill='y')\n",
    "        info = tk.Frame(row, bg=FUNDO_CARD)\n",
    "        info.pack(side='left', fill='both', expand=True, padx=12, pady=8)\n",
    "        top = tk.Frame(info, bg=FUNDO_CARD)\n",
    "        top.pack(fill='x')\n",
    "        tk.Label(top, text=f'BO {bo}', font=FONTE_BODY_BOLD,\n",
    "                 bg=FUNDO_CARD, fg=TEXTO_PRIMARIO).pack(side='left')\n",
    "        tk.Label(top, text=f'  {tag_txt}', font=FONTE_MICRO,\n",
    "                 bg=tag_cor, fg=TEXTO_PRIMARIO,\n",
    "                 padx=6).pack(side='left', padx=8)\n",
    "        tk.Label(top, text=data, font=FONTE_MICRO,\n",
    "                 bg=FUNDO_CARD, fg=TEXTO_TERCIARIO).pack(side='right')\n",
    "        tk.Label(info, text=local, font=FONTE_SMALL,\n",
    "                 bg=FUNDO_CARD, fg=TEXTO_SECUNDARIO, anchor='w').pack(fill='x')\n",
    "        def _bg_rec(w, cor):\n",
    "            try: w.config(bg=cor)\n",
    "            except Exception: pass\n",
    "            for ch in w.winfo_children(): _bg_rec(ch, cor)\n",
    "        def _hin(e): _bg_rec(row, FUNDO_HOVER)\n",
    "        def _hout(e): _bg_rec(row, FUNDO_CARD)\n",
    "        def _abrir(e): self.on_abrir(arq)\n",
    "        row.bind('<Enter>', _hin); row.bind('<Leave>', _hout)\n",
    "        row.bind('<Double-Button-1>', _abrir)\n",
    "        for w in row.winfo_children():\n",
    "            w.bind('<Double-Button-1>', _abrir)\n",
    "\n",
    "    def _abrir_sel(self):\n",
    "        from tkinter import filedialog\n",
    "        cam = filedialog.askopenfilename(\n",
    "            title='Abrir croqui',\n",
    "            filetypes=[('Croquis SICRO', '*.sicro'), ('Todos', '*.*')],\n",
    "            initialdir=DIR_CROQUIS)\n",
    "        if cam:\n",
    "            self.on_abrir(Path(cam))\n",
]

dest = Path("ui") / "tela_inicial.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} ({len(linhas)} linhas)")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")
print("Rode: python main.py")
