"""
criar_via.py — Cria desenho/via_elementos.py
Execute com: python criar_via.py
"""
from pathlib import Path

linhas = [
    "import sys, math\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import AMARELO, BRANCO, COR_PERIGO\n",
    "\n",
    "\n",
    "def desenhar_via(c, el, tx, ty, zoom, fn_mt):\n",
    "    t = el['tipo']\n",
    "    if t in ('_asfalto', '_asfalto_terra'):\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        cor = '#5A4A2A' if t=='_asfalto_terra' else '#606060'\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill=cor,outline='#808080',width=1)\n",
    "    elif t=='_calcada':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill='#A0A0A0',outline='#C0C0C0',width=1)\n",
    "    elif t=='_canteiro':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill='#1A3A1A',outline='')\n",
    "    elif t in ('_faixa_h','_faixa_v'):\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_line(ax1,ay1,ax2,ay2,fill=AMARELO,\n",
    "                      width=max(2,int(2*zoom)),\n",
    "                      dash=(max(8,int(14*zoom)),max(6,int(10*zoom))))\n",
    "    elif t=='_rotatoria':\n",
    "        r=el.get('r',80)*zoom; ri=r*0.4\n",
    "        c.create_oval(tx-r,ty-r,tx+r,ty+r,fill='#606060',outline='')\n",
    "        c.create_oval(tx-ri,ty-ri,tx+ri,ty+ri,fill='#1A3A1A',outline='')\n",
    "        c.create_oval(tx-r,ty-r,tx+r,ty+r,fill='',outline=AMARELO,\n",
    "                      width=max(1,int(1.5*zoom)),dash=(8,5))\n",
    "    elif t=='v_asfalto':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill='#606060',outline='#808080',width=1)\n",
    "    elif t=='v_calcada':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill='#A0A0A0',outline='#C0C0C0',width=1)\n",
    "        p=max(4,int(10*zoom))\n",
    "        for xi in range(int(ax1),int(ax2),p):\n",
    "            c.create_line(xi,int(ay1),xi,int(ay2),fill='#888',width=1)\n",
    "    elif t=='v_conflito':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_rectangle(ax1,ay1,ax2,ay2,fill='',outline=COR_PERIGO,width=2,dash=(8,4))\n",
    "        c.create_text((ax1+ax2)/2,(ay1+ay2)/2,text='CONFLITO',fill=COR_PERIGO,\n",
    "                      font=('Segoe UI',max(8,int(9*zoom)),'bold'))\n",
    "    elif t=='v_faixa_am':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_line(ax1,ay1,ax2,ay2,fill=AMARELO,\n",
    "                      width=max(2,int(3*zoom)),\n",
    "                      dash=(max(10,int(14*zoom)),max(6,int(8*zoom))))\n",
    "    elif t=='v_faixa_br':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        c.create_line(ax1,ay1,ax2,ay2,fill=BRANCO,width=max(2,int(2*zoom)))\n",
    "    elif t=='v_faixa_ped':\n",
    "        ax1,ay1=fn_mt(el['x'],el['y']); ax2,ay2=fn_mt(el['x2'],el['y2'])\n",
    "        larg=max(1,ax2-ax1); n=max(3,int(larg/max(1,8*zoom))); passo=larg/n\n",
    "        for i in range(n):\n",
    "            lx=ax1+i*passo\n",
    "            c.create_rectangle(lx,ay1,lx+passo*0.55,ay2,fill=BRANCO,outline='')\n",
    "    elif t=='v_rotatoria':\n",
    "        r=el.get('r',60)*zoom; ri=r*0.38\n",
    "        c.create_oval(tx-r,ty-r,tx+r,ty+r,fill='#606060',outline='#808080',width=1)\n",
    "        c.create_oval(tx-ri,ty-ri,tx+ri,ty+ri,fill='#1A3A1A',outline='#2A5A2A',width=1)\n",
    "        c.create_oval(tx-r,ty-r,tx+r,ty+r,fill='',outline=AMARELO,\n",
    "                      width=max(1,int(1.5*zoom)),dash=(8,5))\n",
    "    elif t=='v_semaforo':\n",
    "        r=max(5,int(8*zoom)); bw=r*1.6; bh=r*5\n",
    "        c.create_rectangle(tx-bw/2,ty-bh/2,tx+bw/2,ty+bh/2,fill='#111',outline='#444',width=1)\n",
    "        for oy_,cor_ in [(-r*1.6,'#CC2200'),(0,'#CCAA00'),(r*1.6,'#00AA00')]:\n",
    "            c.create_oval(tx-r*0.6,ty+oy_-r*0.6,tx+r*0.6,ty+oy_+r*0.6,\n",
    "                          fill=cor_,outline='#222',width=1)\n",
    "        c.create_line(tx,ty+bh/2,tx,ty+bh/2+r*2,fill='#666',width=max(2,int(2*zoom)))\n",
    "    elif t=='v_placa':\n",
    "        lb=el.get('label','PARE'); r=max(6,int(10*zoom))\n",
    "        cor_p=el.get('cor_placa','#CC0000'); chave_p=el.get('chave_placa','pare')\n",
    "        c.create_line(tx,ty+r,tx,ty+r*2.5,fill='#666',width=max(1,int(1.5*zoom)))\n",
    "        if chave_p=='pare':\n",
    "            pts=[]\n",
    "            for i in range(8):\n",
    "                ang=math.radians(i*45+22.5)\n",
    "                pts.extend([tx+math.cos(ang)*r,ty+math.sin(ang)*r])\n",
    "            c.create_polygon(pts,fill=cor_p,outline=BRANCO,width=max(1,int(1.5*zoom)))\n",
    "            c.create_text(tx,ty,text='PARE',fill=BRANCO,\n",
    "                          font=('Segoe UI',max(5,int(6*zoom)),'bold'))\n",
    "        elif chave_p in ('vel_30','vel_40','vel_60','vel_80'):\n",
    "            c.create_oval(tx-r,ty-r,tx+r,ty+r,fill=BRANCO,\n",
    "                          outline='#CC0000',width=max(2,int(2*zoom)))\n",
    "            c.create_text(tx,ty,text=lb,fill='#CC0000',\n",
    "                          font=('Segoe UI',max(5,int(6*zoom)),'bold'))\n",
    "        elif chave_p=='atencao':\n",
    "            pts=[tx,ty-r,tx+r*0.87,ty+r*0.5,tx-r*0.87,ty+r*0.5]\n",
    "            c.create_polygon(pts,fill=cor_p,outline=BRANCO,width=max(1,int(1.5*zoom)))\n",
    "            c.create_text(tx,ty+3,text='!',fill=BRANCO,\n",
    "                          font=('Segoe UI',max(6,int(8*zoom)),'bold'))\n",
    "        elif chave_p=='proib':\n",
    "            c.create_oval(tx-r,ty-r,tx+r,ty+r,fill=BRANCO,\n",
    "                          outline='#CC0000',width=max(2,int(2*zoom)))\n",
    "            c.create_line(tx-r*.7,ty-r*.7,tx+r*.7,ty+r*.7,\n",
    "                          fill='#CC0000',width=max(2,int(2.5*zoom)))\n",
    "        else:\n",
    "            c.create_rectangle(tx-r,ty-r,tx+r,ty+r,fill=cor_p,outline=BRANCO,\n",
    "                               width=max(1,int(1.5*zoom)))\n",
    "            c.create_text(tx,ty,text=lb[:6],fill=BRANCO,\n",
    "                          font=('Segoe UI',max(5,int(6*zoom)),'bold'))\n",
    "    elif t=='v_arvore':\n",
    "        r=max(8,int(12*zoom))\n",
    "        c.create_oval(tx-r,ty-r,tx+r,ty+r,fill='#1A6A1A',outline='#2A8A2A',width=1)\n",
    "        c.create_oval(tx-r*.5,ty-r*.5,tx+r*.5,ty+r*.5,fill='#2A8A2A',outline='')\n",
    "    elif t=='v_poste':\n",
    "        r=max(3,int(5*zoom))\n",
    "        c.create_line(tx,ty-r*3,tx,ty+r*1.5,fill='#888',width=max(2,int(2*zoom)))\n",
    "        c.create_oval(tx-r,ty-r*4,tx+r,ty-r*2,fill='#FFEE88',outline='#CCCC44',width=1)\n",
    "        c.create_line(tx-r*2,ty-r*3,tx,ty-r*3,fill='#888',width=max(1,int(1.5*zoom)))\n",
]

dest = Path("desenho") / "via_elementos.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import importlib.util
spec = importlib.util.spec_from_file_location("via_elementos", dest)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
print("desenhar_via OK!" if hasattr(mod, "desenhar_via") else "ERRO!")
print("Rode: python main.py")