"""
criar_splash.py — Cria ui/splash.py
Execute com: python criar_splash.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    AZUL_ESCURO, AZUL_MEDIO, AMARELO, BRANCO,\n",
    "    CINZA_CLARO, CINZA_MEDIO, FONTE_PEQ,\n",
    ")\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "\n",
    "\n",
    "class SplashScreen(tk.Toplevel):\n",
    "    \"\"\"\n",
    "    Tela de splash exibida na inicializacao do SICRO PCI/AP.\n",
    "    Mostra brasao, nome do sistema e barra de progresso animada.\n",
    "    Fecha automaticamente apos completar a animacao.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, parent, img_brasao=None):\n",
    "        super().__init__(parent)\n",
    "        self.overrideredirect(True)\n",
    "        w, h = 560, 420\n",
    "        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()\n",
    "        self.geometry(f'{w}x{h}+{(sw-w)//2}+{(sh-h)//2}')\n",
    "        self.configure(bg=AZUL_ESCURO)\n",
    "        self.lift()\n",
    "        self.attributes('-topmost', True)\n",
    "\n",
    "        tk.Frame(self, bg=AMARELO, height=6).pack(fill='x')\n",
    "        corpo = tk.Frame(self, bg=AZUL_ESCURO)\n",
    "        corpo.pack(fill='both', expand=True, padx=48, pady=16)\n",
    "\n",
    "        if img_brasao and PIL_OK:\n",
    "            img = img_brasao.resize((110, 110), Image.LANCZOS)\n",
    "            self._tk = ImageTk.PhotoImage(img)\n",
    "            tk.Label(corpo, image=self._tk, bg=AZUL_ESCURO).pack(pady=(4, 0))\n",
    "        else:\n",
    "            tk.Label(corpo, text='Brasao', font=('Segoe UI', 52),\n",
    "                     bg=AZUL_ESCURO, fg=AMARELO).pack(pady=(4, 0))\n",
    "\n",
    "        tk.Label(corpo, text='POLICIA CIENTIFICA DO AMAPA',\n",
    "                 font=('Segoe UI', 10, 'bold'),\n",
    "                 bg=AZUL_ESCURO, fg=AMARELO).pack(pady=(4, 0))\n",
    "        tk.Label(corpo, text='SICRO PCI/AP',\n",
    "                 font=('Segoe UI', 26, 'bold'),\n",
    "                 bg=AZUL_ESCURO, fg=BRANCO).pack(pady=(6, 0))\n",
    "        tk.Label(corpo, text='Sistema de Croquis Periciais de Transito',\n",
    "                 font=('Segoe UI', 10),\n",
    "                 bg=AZUL_ESCURO, fg=CINZA_CLARO).pack(pady=(2, 0))\n",
    "        tk.Frame(corpo, bg=AZUL_MEDIO, height=1).pack(fill='x', pady=12)\n",
    "        tk.Label(corpo, text='Departamento de Criminalistica - DC',\n",
    "                 font=('Segoe UI', 9),\n",
    "                 bg=AZUL_ESCURO, fg=CINZA_CLARO).pack()\n",
    "        tk.Label(corpo,\n",
    "                 text='Desenvolvido por Andre Ricardo Barroso - Perito Criminal',\n",
    "                 font=('Segoe UI', 9, 'italic'),\n",
    "                 bg=AZUL_ESCURO, fg=CINZA_MEDIO).pack(pady=(3, 12))\n",
    "\n",
    "        sty = ttk.Style()\n",
    "        sty.configure('Sp.Horizontal.TProgressbar',\n",
    "                       troughcolor=AZUL_ESCURO, background=AMARELO,\n",
    "                       borderwidth=0, thickness=6)\n",
    "        self.barra = ttk.Progressbar(corpo, length=380,\n",
    "                                     style='Sp.Horizontal.TProgressbar',\n",
    "                                     maximum=100, value=0)\n",
    "        self.barra.pack()\n",
    "        self.lbl = tk.Label(corpo, text='Inicializando...',\n",
    "                            font=FONTE_PEQ, bg=AZUL_ESCURO, fg=CINZA_MEDIO)\n",
    "        self.lbl.pack(pady=6)\n",
    "        tk.Label(self, text='v16.0.0', font=('Segoe UI', 8),\n",
    "                 bg=AZUL_ESCURO, fg=CINZA_MEDIO).pack(side='right', padx=10)\n",
    "        tk.Frame(self, bg=AMARELO, height=6).pack(fill='x', side='bottom')\n",
    "\n",
    "        self._p = 0\n",
    "        self._anim()\n",
    "\n",
    "    def _anim(self):\n",
    "        if self._p < 100:\n",
    "            self._p += 1.25\n",
    "            self.barra['value'] = self._p\n",
    "            msgs = {\n",
    "                10: 'Carregando interface...',\n",
    "                35: 'Carregando biblioteca...',\n",
    "                60: 'Preparando ferramentas...',\n",
    "                85: 'Quase pronto...',\n",
    "            }\n",
    "            for lim, m in msgs.items():\n",
    "                if int(self._p) == lim:\n",
    "                    self.lbl.config(text=m)\n",
    "            self.after(50, self._anim)\n",
    "\n",
    "    def fechar(self):\n",
    "        self.destroy()\n",
]

dest = Path("ui") / "splash.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")