"""
criar_splash_v2.py — Cria ui/splash.py com novo tema visual
Execute: python criar_splash_v2.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "from tema import (\n",
    "    FUNDO_BASE, FUNDO_PAINEL, FUNDO_ELEVADO,\n",
    "    DOURADO, DOURADO_CLARO, AZUL_MEDIO, AZUL_BORDA,\n",
    "    TEXTO_PRIMARIO, TEXTO_SECUNDARIO, TEXTO_TERCIARIO,\n",
    "    FONTE_DISPLAY, FONTE_H2, FONTE_H3, FONTE_SMALL, FONTE_MICRO,\n",
    "    SPLASH_W, SPLASH_H, SPLASH_DURACAO, SPLASH_MSGS,\n",
    ")\n",
    "\n",
    "\n",
    "class SplashScreen(tk.Toplevel):\n",
    "    \"\"\"\n",
    "    Splash screen do SICRO PCI/AP.\n",
    "    Suporta imagem de fundo PNG opcional (splash_bg.png).\n",
    "    Sem imagem: usa fundo programatico azul escuro.\n",
    "    Com imagem: sobrepos barra e texto sobre a arte.\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, parent, img_brasao=None):\n",
    "        super().__init__(parent)\n",
    "        self.overrideredirect(True)\n",
    "        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()\n",
    "        x = (sw - SPLASH_W) // 2\n",
    "        y = (sh - SPLASH_H) // 2\n",
    "        self.geometry(f'{SPLASH_W}x{SPLASH_H}+{x}+{y}')\n",
    "        self.configure(bg=FUNDO_BASE)\n",
    "        self.lift()\n",
    "        self.attributes('-topmost', True)\n",
    "        self._p = 0.0\n",
    "        self._msg_idx = 0\n",
    "        self._build(img_brasao)\n",
    "        self._anim()\n",
    "\n",
    "    def _build(self, img_brasao):\n",
    "        # Tenta carregar splash_bg.png\n",
    "        bg_path = Path(__file__).parent.parent / 'assets' / 'splash_bg.png'\n",
    "        self._bg_tk = None\n",
    "        if PIL_OK and bg_path.exists():\n",
    "            try:\n",
    "                bg = Image.open(bg_path).resize(\n",
    "                    (SPLASH_W, SPLASH_H), Image.LANCZOS)\n",
    "                self._bg_tk = ImageTk.PhotoImage(bg)\n",
    "            except Exception:\n",
    "                pass\n",
    "\n",
    "        # Canvas principal\n",
    "        self.cv = tk.Canvas(self, width=SPLASH_W, height=SPLASH_H,\n",
    "                            highlightthickness=0, bg=FUNDO_BASE)\n",
    "        self.cv.place(x=0, y=0)\n",
    "\n",
    "        if self._bg_tk:\n",
    "            # Imagem de fundo customizada\n",
    "            self.cv.create_image(0, 0, anchor='nw', image=self._bg_tk)\n",
    "            # Overlay escuro para legibilidade\n",
    "            self.cv.create_rectangle(0, 0, SPLASH_W, SPLASH_H,\n",
    "                                     fill=FUNDO_BASE, stipple='gray50',\n",
    "                                     outline='')\n",
    "        else:\n",
    "            # Fundo programatico\n",
    "            self._desenhar_fundo()\n",
    "\n",
    "        # Faixa dourada topo\n",
    "        self.cv.create_rectangle(0, 0, SPLASH_W, 4,\n",
    "                                 fill=DOURADO, outline='')\n",
    "\n",
    "        # Logo / icone\n",
    "        cy_logo = SPLASH_H * 0.30\n",
    "        if img_brasao and PIL_OK:\n",
    "            try:\n",
    "                img = img_brasao.resize((80, 80), Image.LANCZOS)\n",
    "                self._logo_tk = ImageTk.PhotoImage(img)\n",
    "                self.cv.create_image(SPLASH_W//2, int(cy_logo),\n",
    "                                     anchor='center', image=self._logo_tk)\n",
    "            except Exception:\n",
    "                self._desenhar_icone_fallback(SPLASH_W//2, int(cy_logo))\n",
    "        else:\n",
    "            self._desenhar_icone_fallback(SPLASH_W//2, int(cy_logo))\n",
    "\n",
    "        # Nome SICRO\n",
    "        self.cv.create_text(SPLASH_W//2, int(SPLASH_H*0.48),\n",
    "                            text='SICRO',\n",
    "                            font=('Segoe UI', 38, 'bold'),\n",
    "                            fill=TEXTO_PRIMARIO, anchor='center')\n",
    "\n",
    "        # Subtitulo\n",
    "        self.cv.create_text(SPLASH_W//2, int(SPLASH_H*0.57),\n",
    "                            text='SISTEMA INTELIGENTE DE',\n",
    "                            font=('Segoe UI', 10),\n",
    "                            fill=TEXTO_SECUNDARIO, anchor='center')\n",
    "        self.cv.create_text(SPLASH_W//2, int(SPLASH_H*0.63),\n",
    "                            text='CROQUIS E RECONSTRUCAO DE OCORRENCIAS',\n",
    "                            font=('Segoe UI', 10, 'bold'),\n",
    "                            fill=DOURADO, anchor='center')\n",
    "\n",
    "        # Linha divisoria\n",
    "        lx = SPLASH_W * 0.25\n",
    "        self.cv.create_line(lx, int(SPLASH_H*0.695),\n",
    "                            SPLASH_W-lx, int(SPLASH_H*0.695),\n",
    "                            fill=AZUL_BORDA, width=1)\n",
    "\n",
    "        # Barra de progresso — fundo\n",
    "        bx = int(SPLASH_W * 0.12)\n",
    "        by = int(SPLASH_H * 0.775)\n",
    "        bw = SPLASH_W - bx*2\n",
    "        bh = 5\n",
    "        self.cv.create_rectangle(bx, by, bx+bw, by+bh,\n",
    "                                 fill=FUNDO_ELEVADO, outline=AZUL_BORDA,\n",
    "                                 width=1)\n",
    "        self._bx = bx; self._by = by; self._bw = bw; self._bh = bh\n",
    "\n",
    "        # Barra de progresso — preenchimento (começa vazio)\n",
    "        self._barra_id = self.cv.create_rectangle(\n",
    "            bx, by, bx, by+bh,\n",
    "            fill=DOURADO, outline='', width=0)\n",
    "\n",
    "        # Texto de status\n",
    "        self._status_id = self.cv.create_text(\n",
    "            SPLASH_W//2, int(SPLASH_H*0.835),\n",
    "            text='Inicializando sistema...',\n",
    "            font=('Segoe UI', 9),\n",
    "            fill=TEXTO_SECUNDARIO, anchor='center')\n",
    "\n",
    "        # Percentual\n",
    "        self._pct_id = self.cv.create_text(\n",
    "            bx+bw, by-8,\n",
    "            text='0%',\n",
    "            font=('Segoe UI', 8, 'bold'),\n",
    "            fill=DOURADO, anchor='e')\n",
    "\n",
    "        # Rodape: PCI/AP\n",
    "        self.cv.create_text(SPLASH_W//2, int(SPLASH_H*0.93),\n",
    "                            text='POLICIA CIENTIFICA DO AMAPA  |  Departamento de Criminalistica',\n",
    "                            font=('Segoe UI', 8),\n",
    "                            fill=TEXTO_TERCIARIO, anchor='center')\n",
    "\n",
    "        # Versao\n",
    "        self.cv.create_text(SPLASH_W-12, SPLASH_H-12,\n",
    "                            text='v1.0.0-alpha',\n",
    "                            font=('Segoe UI', 8),\n",
    "                            fill=TEXTO_TERCIARIO, anchor='se')\n",
    "\n",
    "        # Faixa dourada base\n",
    "        self.cv.create_rectangle(0, SPLASH_H-4, SPLASH_W, SPLASH_H,\n",
    "                                 fill=DOURADO, outline='')\n",
    "\n",
    "    def _desenhar_fundo(self):\n",
    "        \"\"\"Fundo programatico com grid tecnico leve.\"\"\"\n",
    "        c = self.cv\n",
    "        # Gradiente simulado com retangulos\n",
    "        c.create_rectangle(0, 0, SPLASH_W, SPLASH_H//2,\n",
    "                           fill='#0D1830', outline='')\n",
    "        c.create_rectangle(0, SPLASH_H//2, SPLASH_W, SPLASH_H,\n",
    "                           fill='#0A1020', outline='')\n",
    "        # Grid tecnico leve\n",
    "        for x in range(0, SPLASH_W, 40):\n",
    "            c.create_line(x, 0, x, SPLASH_H, fill='#111E38', width=1)\n",
    "        for y in range(0, SPLASH_H, 40):\n",
    "            c.create_line(0, y, SPLASH_W, y, fill='#111E38', width=1)\n",
    "        # Circulo de glow central\n",
    "        cx, cy = SPLASH_W//2, SPLASH_H//2\n",
    "        for r, alpha in [(200,'#0D1A3A'),(150,'#0F1E42'),(100,'#111E38')]:\n",
    "            c.create_oval(cx-r, cy-r, cx+r, cy+r,\n",
    "                          fill=alpha, outline='')\n",
    "\n",
    "    def _desenhar_icone_fallback(self, cx, cy):\n",
    "        \"\"\"Icone geometrico simples quando nao ha brasao.\"\"\"\n",
    "        c = self.cv; r = 30\n",
    "        # Losango externo\n",
    "        pts = [cx, cy-r, cx+r*0.7, cy, cx, cy+r, cx-r*0.7, cy]\n",
    "        c.create_polygon(pts, fill='', outline=DOURADO, width=2)\n",
    "        # Cruz de mira\n",
    "        c.create_line(cx, cy-r*0.6, cx, cy+r*0.6, fill=TEXTO_PRIMARIO, width=1)\n",
    "        c.create_line(cx-r*0.6, cy, cx+r*0.6, cy, fill=TEXTO_PRIMARIO, width=1)\n",
    "        # Circulo central\n",
    "        c.create_oval(cx-8, cy-8, cx+8, cy+8,\n",
    "                      fill='', outline=AZUL_MEDIO, width=2)\n",
    "        c.create_oval(cx-3, cy-3, cx+3, cy+3, fill=DOURADO, outline='')\n",
    "\n",
    "    def _anim(self):\n",
    "        \"\"\"Anima a barra de progresso.\"\"\"\n",
    "        if self._p >= 100:\n",
    "            return\n",
    "        # Velocidade: completa em SPLASH_DURACAO ms\n",
    "        # step a cada 50ms\n",
    "        step = 100 / (SPLASH_DURACAO / 50)\n",
    "        self._p = min(100, self._p + step)\n",
    "\n",
    "        # Atualiza barra\n",
    "        largura = int(self._bw * self._p / 100)\n",
    "        self.cv.coords(self._barra_id,\n",
    "                       self._bx, self._by,\n",
    "                       self._bx + largura, self._by + self._bh)\n",
    "\n",
    "        # Atualiza percentual\n",
    "        self.cv.itemconfig(self._pct_id, text=f'{int(self._p)}%')\n",
    "\n",
    "        # Atualiza mensagem\n",
    "        msg_atual = SPLASH_MSGS[0][1]\n",
    "        for pct, msg in SPLASH_MSGS:\n",
    "            if self._p >= pct:\n",
    "                msg_atual = msg\n",
    "        self.cv.itemconfig(self._status_id, text=msg_atual)\n",
    "\n",
    "        self.after(50, self._anim)\n",
    "\n",
    "    def fechar(self):\n",
    "        self.destroy()\n",
]

dest = Path("ui") / "splash.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} ({len(linhas)} linhas)")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")