"""
criar_dialogo_caso.py — Cria ui/dialogo_caso.py
Execute com: python criar_dialogo_caso.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import datetime\n",
    "import calendar\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    COR_FUNDO, COR_PAINEL, COR_CARD, COR_BORDA,\n",
    "    COR_TEXTO_SEC, AMARELO, BRANCO, CINZA_CLARO, CINZA_MEDIO,\n",
    "    AZUL_MEDIO, AZUL_CLARO, PRETO_SOFT,\n",
    "    FONTE_SUB, FONTE_NORMAL, FONTE_PEQ,\n",
    "    MUNICIPIOS_AP,\n",
    ")\n",
    "\n",
    "\n",
    "class CalendarioPopup(tk.Toplevel):\n",
    "    \"\"\"Calendario nativo em Tkinter puro, sem dependencias externas.\"\"\"\n",
    "\n",
    "    def __init__(self, parent, entry_destino):\n",
    "        super().__init__(parent)\n",
    "        self.entry = entry_destino\n",
    "        self.overrideredirect(True)\n",
    "        self.configure(bg=COR_PAINEL)\n",
    "        self.attributes('-topmost', True)\n",
    "        try:\n",
    "            d, m, y = entry_destino.get().strip().split('/')\n",
    "            self._data = datetime.date(int(y), int(m), int(d))\n",
    "        except Exception:\n",
    "            self._data = datetime.date.today()\n",
    "        self._ano = self._data.year\n",
    "        self._mes = self._data.month\n",
    "        self.update_idletasks()\n",
    "        ex = entry_destino.winfo_rootx()\n",
    "        ey = entry_destino.winfo_rooty() + entry_destino.winfo_height()\n",
    "        self.geometry(f'260x240+{ex}+{ey}')\n",
    "        self.lift()\n",
    "        self._build()\n",
    "        self.bind('<FocusOut>', lambda e: self.after(100, self._fechar_se_fora))\n",
    "        self.focus_force()\n",
    "\n",
    "    def _fechar_se_fora(self):\n",
    "        try:\n",
    "            if not self.focus_get():\n",
    "                self.destroy()\n",
    "        except Exception:\n",
    "            self.destroy()\n",
    "\n",
    "    def _build(self):\n",
    "        for w in self.winfo_children():\n",
    "            w.destroy()\n",
    "        tk.Frame(self, bg=AMARELO, height=3).pack(fill='x')\n",
    "        nav = tk.Frame(self, bg=COR_PAINEL)\n",
    "        nav.pack(fill='x', padx=4, pady=4)\n",
    "        tk.Button(nav, text='<', font=('Segoe UI',10), width=2,\n",
    "                  bg=COR_PAINEL, fg=BRANCO, relief='flat', cursor='hand2',\n",
    "                  command=self._mes_anterior).pack(side='left')\n",
    "        tk.Button(nav, text='>', font=('Segoe UI',10), width=2,\n",
    "                  bg=COR_PAINEL, fg=BRANCO, relief='flat', cursor='hand2',\n",
    "                  command=self._mes_seguinte).pack(side='right')\n",
    "        MESES = ['Janeiro','Fevereiro','Marco','Abril','Maio','Junho',\n",
    "                 'Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']\n",
    "        tk.Label(nav, text=f'{MESES[self._mes-1]} {self._ano}',\n",
    "                 font=('Segoe UI',10,'bold'),\n",
    "                 bg=COR_PAINEL, fg=AMARELO).pack(expand=True)\n",
    "        dias_sem = tk.Frame(self, bg=COR_PAINEL)\n",
    "        dias_sem.pack(fill='x', padx=4)\n",
    "        for ds in ['Dom','Seg','Ter','Qua','Qui','Sex','Sab']:\n",
    "            tk.Label(dias_sem, text=ds, font=('Segoe UI',8),\n",
    "                     bg=COR_PAINEL, fg=CINZA_MEDIO, width=3).pack(side='left')\n",
    "        tk.Frame(self, bg=COR_BORDA, height=1).pack(fill='x', padx=4, pady=2)\n",
    "        grid = tk.Frame(self, bg=COR_PAINEL)\n",
    "        grid.pack(fill='both', expand=True, padx=4, pady=2)\n",
    "        cal = calendar.monthcalendar(self._ano, self._mes)\n",
    "        hoje = datetime.date.today()\n",
    "        for semana in cal:\n",
    "            row_f = tk.Frame(grid, bg=COR_PAINEL)\n",
    "            row_f.pack(fill='x')\n",
    "            for dia in semana:\n",
    "                if dia == 0:\n",
    "                    tk.Label(row_f, text='', width=3, bg=COR_PAINEL).pack(side='left')\n",
    "                else:\n",
    "                    d = datetime.date(self._ano, self._mes, dia)\n",
    "                    is_hoje = (d == hoje)\n",
    "                    is_sel  = (d == self._data)\n",
    "                    bg = AMARELO if is_sel else AZUL_MEDIO if is_hoje else COR_PAINEL\n",
    "                    fg = PRETO_SOFT if is_sel else BRANCO\n",
    "                    tk.Button(row_f, text=str(dia), width=3,\n",
    "                              font=('Segoe UI',9,'bold' if is_hoje or is_sel else 'normal'),\n",
    "                              bg=bg, fg=fg,\n",
    "                              activebackground=AZUL_CLARO,\n",
    "                              relief='flat', cursor='hand2',\n",
    "                              command=lambda d=d: self._selecionar(d)).pack(side='left')\n",
    "        tk.Frame(self, bg=AMARELO, height=3).pack(fill='x', side='bottom')\n",
    "\n",
    "    def _mes_anterior(self):\n",
    "        if self._mes == 1: self._mes=12; self._ano-=1\n",
    "        else: self._mes -= 1\n",
    "        self._build()\n",
    "\n",
    "    def _mes_seguinte(self):\n",
    "        if self._mes == 12: self._mes=1; self._ano+=1\n",
    "        else: self._mes += 1\n",
    "        self._build()\n",
    "\n",
    "    def _selecionar(self, data):\n",
    "        self._data = data\n",
    "        self.entry.delete(0, tk.END)\n",
    "        self.entry.insert(0, data.strftime('%d/%m/%Y'))\n",
    "        self.destroy()\n",
    "\n",
    "\n",
    "class DialogoDadosCaso(tk.Toplevel):\n",
    "    \"\"\"Formulario de dados do caso: BO, requisicao, local, municipio, perito, data.\"\"\"\n",
    "\n",
    "    def __init__(self, parent, modo='zero'):\n",
    "        super().__init__(parent)\n",
    "        self.title('Dados do caso')\n",
    "        self.configure(bg=COR_FUNDO)\n",
    "        self.resizable(False, False)\n",
    "        self.grab_set()\n",
    "        self.resultado = None\n",
    "        w, h = 480, 400\n",
    "        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()\n",
    "        self.geometry(f'{w}x{h}+{(sw-w)//2}+{(sh-h)//2}')\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x')\n",
    "        corpo = tk.Frame(self, bg=COR_FUNDO)\n",
    "        corpo.pack(fill='both', expand=True, padx=24, pady=16)\n",
    "        titulo = 'Croqui do zero' if modo=='zero' else 'Croqui sobre drone'\n",
    "        tk.Label(corpo, text=f'  {titulo}',\n",
    "                 font=FONTE_SUB, bg=COR_FUNDO, fg=AMARELO).pack(anchor='w', pady=(0,12))\n",
    "        campos = [\n",
    "            ('No do BO',           'bo',         ''),\n",
    "            ('No da Requisicao',   'requisicao',  ''),\n",
    "            ('Local (ruas/av.)',   'local',       ''),\n",
    "            ('Municipio',          'municipio',   'Porto Grande'),\n",
    "            ('Perito responsavel', 'perito',      'Andre Ricardo Barroso'),\n",
    "            ('Data do exame',      'data',        datetime.date.today().strftime('%d/%m/%Y')),\n",
    "        ]\n",
    "        self.entradas = {}\n",
    "        self._dd_win  = None\n",
    "        for label, chave, ph in campos:\n",
    "            row = tk.Frame(corpo, bg=COR_FUNDO)\n",
    "            row.pack(fill='x', pady=3)\n",
    "            tk.Label(row, text=label, font=FONTE_PEQ, width=20,\n",
    "                     anchor='w', bg=COR_FUNDO, fg=COR_TEXTO_SEC).pack(side='left')\n",
    "            if chave == 'municipio':\n",
    "                e = self._campo_municipio(row, ph)\n",
    "            elif chave == 'data':\n",
    "                e = self._campo_data(row, ph)\n",
    "            else:\n",
    "                e = tk.Entry(row, font=FONTE_NORMAL,\n",
    "                             bg=COR_CARD, fg=BRANCO,\n",
    "                             insertbackground=BRANCO, relief='flat', bd=4)\n",
    "                e.insert(0, ph)\n",
    "                e.pack(side='left', fill='x', expand=True)\n",
    "            self.entradas[chave] = e\n",
    "        tk.Frame(corpo, bg=COR_BORDA, height=1).pack(fill='x', pady=10)\n",
    "        btns = tk.Frame(corpo, bg=COR_FUNDO)\n",
    "        btns.pack(fill='x')\n",
    "        tk.Button(btns, text='Cancelar', font=FONTE_NORMAL, cursor='hand2',\n",
    "                  bg=COR_CARD, fg=COR_TEXTO_SEC, activebackground=COR_BORDA,\n",
    "                  relief='flat', padx=14, pady=5,\n",
    "                  command=self.destroy).pack(side='right', padx=(6,0))\n",
    "        tk.Button(btns, text='Criar croqui ->',\n",
    "                  font=('Segoe UI',10,'bold'), cursor='hand2',\n",
    "                  bg=AZUL_MEDIO, fg=BRANCO, activebackground=AZUL_CLARO,\n",
    "                  relief='flat', padx=14, pady=5,\n",
    "                  command=self._ok).pack(side='right')\n",
    "        tk.Frame(self, bg=AMARELO, height=4).pack(fill='x', side='bottom')\n",
    "\n",
    "    def _campo_municipio(self, row, ph):\n",
    "        mframe = tk.Frame(row, bg=COR_CARD)\n",
    "        mframe.pack(side='left', fill='x', expand=True)\n",
    "        e = tk.Entry(mframe, font=FONTE_NORMAL,\n",
    "                     bg=COR_CARD, fg=BRANCO,\n",
    "                     insertbackground=BRANCO, relief='flat', bd=4)\n",
    "        e.insert(0, ph)\n",
    "        e.pack(side='left', fill='x', expand=True)\n",
    "        btn_dd = tk.Button(mframe, text='v', font=('Segoe UI',10),\n",
    "                           bg=COR_CARD, fg=CINZA_CLARO,\n",
    "                           activebackground=AZUL_MEDIO,\n",
    "                           relief='flat', cursor='hand2', padx=4)\n",
    "        btn_dd.pack(side='right')\n",
    "\n",
    "        def _fechar_dd():\n",
    "            if self._dd_win and self._dd_win.winfo_exists():\n",
    "                self._dd_win.destroy()\n",
    "            self._dd_win = None\n",
    "\n",
    "        def _mostrar_dd(lista, entry=e):\n",
    "            _fechar_dd()\n",
    "            self.update_idletasks()\n",
    "            ex = mframe.winfo_rootx()\n",
    "            ey = mframe.winfo_rooty() + mframe.winfo_height()\n",
    "            ew = mframe.winfo_width()\n",
    "            altura = min(len(lista), 10) * 24\n",
    "            win = tk.Toplevel(self)\n",
    "            win.overrideredirect(True)\n",
    "            win.geometry(f'{ew}x{altura}+{ex}+{ey}')\n",
    "            win.configure(bg=COR_CARD)\n",
    "            win.attributes('-topmost', True)\n",
    "            win.lift()\n",
    "            self._dd_win = win\n",
    "            lb2 = tk.Listbox(win, bg='#1A2A5A', fg=BRANCO,\n",
    "                             selectbackground=AZUL_MEDIO,\n",
    "                             selectforeground=BRANCO,\n",
    "                             font=FONTE_NORMAL, relief='flat', bd=0,\n",
    "                             activestyle='dotbox',\n",
    "                             highlightthickness=1,\n",
    "                             highlightcolor=AZUL_MEDIO)\n",
    "            lb2.pack(fill='both', expand=True)\n",
    "            for m in lista:\n",
    "                lb2.insert(tk.END, f'  {m}')\n",
    "            def _sel_dd(event, entry=entry):\n",
    "                idx = lb2.nearest(event.y)\n",
    "                if idx >= 0:\n",
    "                    lb2.selection_clear(0, tk.END)\n",
    "                    lb2.selection_set(idx)\n",
    "                    val = lb2.get(idx).strip()\n",
    "                    entry.delete(0, tk.END)\n",
    "                    entry.insert(0, val)\n",
    "                win.after(200, _fechar_dd)\n",
    "            lb2.bind('<Button-1>', _sel_dd)\n",
    "\n",
    "        def _ao_digitar(event, entry=e):\n",
    "            txt = entry.get().lower()\n",
    "            filtrados = [m for m in MUNICIPIOS_AP if txt in m.lower()]\n",
    "            if filtrados and txt:\n",
    "                _mostrar_dd(filtrados, entry)\n",
    "            else:\n",
    "                _fechar_dd()\n",
    "\n",
    "        def _toggle_dd(entry=e):\n",
    "            if self._dd_win and self._dd_win.winfo_exists():\n",
    "                _fechar_dd()\n",
    "            else:\n",
    "                _mostrar_dd(MUNICIPIOS_AP, entry)\n",
    "\n",
    "        e.bind('<KeyRelease>', _ao_digitar)\n",
    "        e.bind('<Escape>', lambda ev: _fechar_dd())\n",
    "        btn_dd.config(command=_toggle_dd)\n",
    "        return e\n",
    "\n",
    "    def _campo_data(self, row, ph):\n",
    "        dframe = tk.Frame(row, bg=COR_CARD)\n",
    "        dframe.pack(side='left', fill='x', expand=True)\n",
    "        e = tk.Entry(dframe, font=FONTE_NORMAL,\n",
    "                     bg=COR_CARD, fg=BRANCO,\n",
    "                     insertbackground=BRANCO, relief='flat', bd=4)\n",
    "        e.insert(0, datetime.date.today().strftime('%d/%m/%Y'))\n",
    "        e.pack(side='left', fill='x', expand=True)\n",
    "        btn_cal = tk.Button(dframe, text='Cal', font=('Segoe UI',10),\n",
    "                            bg=COR_CARD, fg=AMARELO,\n",
    "                            activebackground=AZUL_MEDIO,\n",
    "                            relief='flat', cursor='hand2', padx=4)\n",
    "        btn_cal.pack(side='right')\n",
    "        btn_cal.config(command=lambda: CalendarioPopup(self, e))\n",
    "        e.bind('<Button-1>', lambda ev: CalendarioPopup(self, e))\n",
    "        return e\n",
    "\n",
    "    def _ok(self):\n",
    "        self.resultado = {k: v.get().strip() for k,v in self.entradas.items()}\n",
    "        self.destroy()\n",
]

dest = Path("ui") / "dialogo_caso.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")