"""
criar_tela_inicial.py — Cria ui/tela_inicial.py
Execute com: python criar_tela_inicial.py
"""
from pathlib import Path

linhas = [
    "import tkinter as tk\n",
    "import datetime\n",
    "import json\n",
    "import sys\n",
    "from pathlib import Path\n",
    "_raiz = Path(__file__).parent.parent\n",
    "if str(_raiz) not in sys.path:\n",
    "    sys.path.insert(0, str(_raiz))\n",
    "from config import (\n",
    "    COR_FUNDO, COR_PAINEL, COR_CARD, COR_BORDA,\n",
    "    COR_TEXTO, COR_TEXTO_SEC,\n",
    "    AMARELO, BRANCO, CINZA_CLARO, CINZA_MEDIO, CINZA_ESCURO,\n",
    "    AZUL_MEDIO, AZUL_CLARO,\n",
    "    FONTE_SUB, FONTE_NORMAL, FONTE_PEQ,\n",
    "    DIR_CROQUIS,\n",
    ")\n",
    "try:\n",
    "    from PIL import Image, ImageTk\n",
    "    PIL_OK = True\n",
    "except ImportError:\n",
    "    PIL_OK = False\n",
    "\n",
    "\n",
    "class TelaInicial(tk.Frame):\n",
    "    \"\"\"\n",
    "    Tela inicial do SICRO PCI/AP.\n",
    "    Exibe botoes para criar novo croqui e a biblioteca de croquis salvos.\n",
    "\n",
    "    Callbacks:\n",
    "      on_novo(modo)     — chamado ao clicar em novo croqui ('zero' ou 'drone')\n",
    "      on_abrir(caminho) — chamado ao abrir um croqui da biblioteca\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, master, on_novo, on_abrir, img_brasao=None):\n",
    "        super().__init__(master, bg=COR_FUNDO)\n",
    "        self.on_novo    = on_novo\n",
    "        self.on_abrir   = on_abrir\n",
    "        self.img_brasao = img_brasao\n",
    "        self._build()\n",
    "\n",
    "    def _build(self):\n",
    "        # Cabecalho\n",
    "        cab = tk.Frame(self, bg=COR_PAINEL)\n",
    "        cab.pack(fill='x')\n",
    "        tk.Frame(cab, bg=AMARELO, height=4).pack(fill='x')\n",
    "        inner = tk.Frame(cab, bg=COR_PAINEL)\n",
    "        inner.pack(fill='x', padx=20, pady=10)\n",
    "        if self.img_brasao and PIL_OK:\n",
    "            img = self.img_brasao.resize((40, 40), Image.LANCZOS)\n",
    "            self._hdr_tk = ImageTk.PhotoImage(img)\n",
    "            tk.Label(inner, image=self._hdr_tk,\n",
    "                     bg=COR_PAINEL).pack(side='left', padx=(0,10))\n",
    "        tk.Label(inner, text='SICRO PCI/AP', font=('Segoe UI',14,'bold'),\n",
    "                 bg=COR_PAINEL, fg=BRANCO).pack(side='left')\n",
    "        tk.Label(inner, text='Policia Cientifica do Amapa',\n",
    "                 font=FONTE_PEQ, bg=COR_PAINEL, fg=AMARELO).pack(side='left', padx=10)\n",
    "        tk.Label(inner, text=datetime.date.today().strftime('%d/%m/%Y'),\n",
    "                 font=FONTE_PEQ, bg=COR_PAINEL, fg=CINZA_MEDIO).pack(side='right')\n",
    "\n",
    "        # Corpo\n",
    "        corpo = tk.Frame(self, bg=COR_FUNDO)\n",
    "        corpo.pack(fill='both', expand=True, padx=24, pady=18)\n",
    "\n",
    "        # Coluna esquerda: novo croqui\n",
    "        esq = tk.Frame(corpo, bg=COR_FUNDO)\n",
    "        esq.pack(side='left', fill='y', padx=(0,16))\n",
    "        tk.Label(esq, text='Novo croqui', font=FONTE_SUB,\n",
    "                 bg=COR_FUNDO, fg=AMARELO).pack(anchor='w', pady=(0,8))\n",
    "        self._card(esq, 'Croqui do zero',\n",
    "                   'Sem imagem de fundo\\ndesenho vetorial completo',\n",
    "                   AZUL_MEDIO, lambda: self.on_novo('zero'))\n",
    "        self._card(esq, 'Croqui sobre drone',\n",
    "                   'Carrega foto aerea\\ncalibra escala pela lona',\n",
    "                   CINZA_ESCURO, lambda: self.on_novo('drone'))\n",
    "\n",
    "        tk.Frame(corpo, bg=COR_BORDA, width=1).pack(side='left', fill='y', padx=4)\n",
    "\n",
    "        # Coluna direita: biblioteca\n",
    "        dir_ = tk.Frame(corpo, bg=COR_FUNDO)\n",
    "        dir_.pack(side='left', fill='both', expand=True)\n",
    "        topo = tk.Frame(dir_, bg=COR_FUNDO)\n",
    "        topo.pack(fill='x')\n",
    "        tk.Label(topo, text='Biblioteca de croquis', font=FONTE_SUB,\n",
    "                 bg=COR_FUNDO, fg=AMARELO).pack(side='left')\n",
    "        tk.Button(topo, text='Atualizar', font=FONTE_PEQ, cursor='hand2',\n",
    "                  bg=COR_CARD, fg=COR_TEXTO_SEC, activebackground=COR_BORDA,\n",
    "                  relief='flat', command=self._carregar).pack(side='right')\n",
    "        flb = tk.Frame(dir_, bg=COR_CARD)\n",
    "        flb.pack(fill='both', expand=True, pady=6)\n",
    "        scrl = tk.Scrollbar(flb)\n",
    "        scrl.pack(side='right', fill='y')\n",
    "        self.lb = tk.Listbox(flb, yscrollcommand=scrl.set,\n",
    "                             bg=COR_CARD, fg=COR_TEXTO,\n",
    "                             selectbackground=AZUL_MEDIO,\n",
    "                             selectforeground=BRANCO,\n",
    "                             font=FONTE_NORMAL, relief='flat', bd=0,\n",
    "                             activestyle='none', highlightthickness=0)\n",
    "        self.lb.pack(fill='both', expand=True, padx=2)\n",
    "        scrl.config(command=self.lb.yview)\n",
    "        self.lb.bind('<Double-Button-1>', self._abrir_sel)\n",
    "        tk.Button(dir_, text='Abrir croqui selecionado ->',\n",
    "                  font=FONTE_NORMAL, cursor='hand2',\n",
    "                  bg=AZUL_MEDIO, fg=BRANCO,\n",
    "                  activebackground=AZUL_CLARO,\n",
    "                  relief='flat', pady=7,\n",
    "                  command=self._abrir_sel).pack(fill='x')\n",
    "        self._carregar()\n",
    "\n",
    "    def _card(self, parent, titulo, desc, cor, cmd):\n",
    "        f = tk.Frame(parent, bg=COR_CARD, cursor='hand2')\n",
    "        f.pack(fill='x', pady=4, ipadx=12, ipady=10)\n",
    "        tk.Frame(f, bg=cor, width=4).pack(side='left', fill='y')\n",
    "        inner = tk.Frame(f, bg=COR_CARD)\n",
    "        inner.pack(side='left', padx=10)\n",
    "        tk.Label(inner, text=titulo, font=('Segoe UI',11,'bold'),\n",
    "                 bg=COR_CARD, fg=BRANCO).pack(anchor='w')\n",
    "        tk.Label(inner, text=desc, font=FONTE_PEQ,\n",
    "                 bg=COR_CARD, fg=CINZA_CLARO, justify='left').pack(anchor='w')\n",
    "        for w in [f, inner] + list(inner.winfo_children()):\n",
    "            w.bind('<Button-1>', lambda e, c=cmd: c())\n",
    "        f.bind('<Enter>', lambda e: f.config(bg='#1E2A60'))\n",
    "        f.bind('<Leave>', lambda e: f.config(bg=COR_CARD))\n",
    "\n",
    "    def _carregar(self):\n",
    "        self.lb.delete(0, tk.END)\n",
    "        self._arqs = sorted(DIR_CROQUIS.glob('*.sicro'), reverse=True)\n",
    "        if not self._arqs:\n",
    "            self.lb.insert(tk.END, '  (nenhum croqui salvo)')\n",
    "            return\n",
    "        for a in self._arqs:\n",
    "            try:\n",
    "                with open(a) as f:\n",
    "                    d = json.load(f)\n",
    "                self.lb.insert(tk.END,\n",
    "                    f\"  BO {d.get('bo','?')}  .  {d.get('data','')}  .  \"\n",
    "                    f\"{d.get('local', a.stem)[:40]}\")\n",
    "            except Exception:\n",
    "                self.lb.insert(tk.END, f'  {a.name}')\n",
    "\n",
    "    def _abrir_sel(self, event=None):\n",
    "        idx = self.lb.curselection()\n",
    "        if not idx or not hasattr(self, '_arqs'): return\n",
    "        if idx[0] < len(self._arqs):\n",
    "            self.on_abrir(self._arqs[idx[0]])\n",
]

dest = Path("ui") / "tela_inicial.py"
dest.write_text("".join(linhas), encoding="utf-8")
print(f"OK — {dest} criado com {len(linhas)} linhas")

import ast
try:
    ast.parse(dest.read_text(encoding="utf-8"))
    print("Sintaxe OK")
except SyntaxError as e:
    print(f"ERRO: {e}")

print("Rode: python main.py")